# -------- IMPORTANT -------------------
# If your website is supposed to be placed in a subdirectory under a domain name
# e.g., http://example.com/my-project/ when it is published, you must use
# `relativeurls = true` in config.toml
# See below the relevant value for the different chains, local dev/production


#------- LOCAL DEVELOPMENT/TESTING -------
# remember ending '/'
#baseurl = "/"
#relativeurls = true
# see .Rprofile for publishDir, i.e. the place
# where generated HTML is put (the "public" dir in hugo parlance)
#-----------------------------------------


#--------------- PRODUCTION ---------------
# remember ending '/'
baseurl = "http://www.eurocontrol.int/prudata/dashboard/"
relativeurls = false
# the following is alsready setup in .Rprofile for the project
# publishDir = "../ses-portal-generated"
#-----------------------------------------

# for EUROCONTROL test website
#baseurl = "https://www-test.eurocontrol.int/ansperf-test/dataportal/ses-test/"
#relativeurls = false

#


languageCode = "en-us"
title = "Single European Sky Portal"
theme = "hugo-lithium"

#######   DO NOT ACTIVATE VIA THE THEME            #########
#######   EUROCONTROL CSP DOES NOT ALLOW INLINE JS #########
#######   see relevant load_google_analytics.js    #########
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["RSS"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "News"
    url = "/post/"
    weight = 10
[[menu.main]]
    name = "Dashboard"
    url = "/vis/"
    weight = 20
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 30
[[menu.main]]
    name = "Metadata"
    url = "/metadata/"
    weight = 40
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 100

[params]
    description = "Single European Sky Portal."
    privacyURL = "https://www.eurocontrol.int/info/privacy-and-website-terms-use"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    image = "ses-performance-logo.png"
    width = ""
    height = "32"
    alt = "Single European Sky logo"

    [params.poweredBy]
#    image = "powered-by-eurocontrol-logo.png"
#    url = "https://www.eurocontrol.int/"
#    width = ""
#    height = "56"
#    alt = "EUROCONTROL"

    [params.poweredByFooter]
    image = "euctrl-logo-wide-poweredby.svg"
    url = "https://www.eurocontrol.int/"
    width = ""
    height = "h2"
    alt = "EUROCONTROL"

    [params.logofooter]
    image = "logo-ce-horizontal-en-quadri-lr.png"
    url = "https://webgate.ec.europa.eu/eusinglesky/node_en"
    width = "w6"
    height = "h2"
    alt = "European Commission logo"
    description = "Single European Sky, "
