---
title: Additional ASMA Time
categories:
  - metadata
  - glossary
---

<style>
table, td {
  border: 1px solid #AAAAAA;
  border-collapse: collapse;
}
td {
  padding: 5px;
}
</style>

## Contacts

|||
|---------------------------|------------------------------------------------------------------------------------|
| Contact organisation      | EUROCONTROL: The European organisation for the safety of air navigation            |
| Contact organisation unit |	Directorate European Civil-Military Aviation - Performance Review Unit (DECMA/PRU) |
| Contact name              |	Performance Review Unit - EUROCONTROL                                              |
| Contact mail address      | 96 Rue de la Fusée<br>1130 Brussels<br>Belgium                                     |
| Contact e-mail address    | [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int)                  |

## Metadata update

|||
|-------------------------|-------------------|
| Metadata last certified | not applicable    |
| Metadata last update 	  | 01 November 2016  |


## Statistical presentation

### Data description

The **additional ASMA time** is a proxy for the average arrival runway queuing time on the
inbound traffic flow, during congestion periods at airports.

It is the difference between the actual ASMA time of a flight and a statistically determined
[unimpeded ASMA time][uasma] based on ASMA times in periods of low traffic demand (see also
[unimpeded ASMA time - Methodology][uasmamet]).

Uncertainty of approach conditions (e.g. pilot performance, landing clearance time, approach speed, wind conditions) makes traffic supply to runways a stochastic phenomenon. In order to ensure continuous traffic demand at runways and maximise runway usage, a minimum level of queuing is required. However, additional time in holding is detrimental to operations efficiency, fuel consumption and environment. Therefore, there exists a trade-off between approach efficiency and runway throughput.

As an output of the ATMAP Group, the additional ASMA time PI has been in use as a commonly agreed proxy for airport inefficiencies in the approach phase since 2008 and is compliant with the [KPI][kpi] definition in EU legislation.


### Classification system

Additional ASMA time is classified per Member State, with a breakdown for each airport subject to performance monitoring within the SES performance scheme.


### Sector coverage

The measures pertain to the [Air Transport and Air Traffic Management Sector][air-stats]
of the economy. 


### Statistical concepts and definitions

The **Arrival Sequencing and Metering Area (ASMA)** is defined as a virtual cylinder with a
40-NM radius around the airport.
The actual time spent by a flight between its last entry in the cylinder
(Entry-time at 40 NM upstream) and the actual landing time (ALDT) is denoted **ASMA transit time**.

A [Unimpeded ASMA time][uasma] is determined for each group of flights with the same parameters
(i.e. aircraft class, ASMA entry sector, arrival runway) and represents the transit time
in non congested conditions.

The **Additional ASMA time** is the difference between the actual ASMA transit time and
the unimpeded ASMA time calculated for non-congested conditions. 


### Statistical unit
The statistical unit is the airport. Airport level data is also aggregated to States.

### Statistical population
The statistical population is the set of airports subject to performance monitoring within the
SES performance scheme.

### Reference area

The reference area is the [Single European Sky Area][ses-area]. 


### Time coverage
2011 is the first year for which data is presented.

### Base period
Not applicable.


## Unit of Measure
The additional ASMA time is measured in minutes per [IFR][ifr] arrival [min/arr].


## Reference period

* The first reference period (RP1) covers the calendar years 2012 to 2014 inclusive.
* The second reference period (RP2) covers the calendar years 2015 to 2019 inclusive. 

Unless decided otherwise, the following reference periods shall be of five calendar years. 

## Institutional Mandate
Legal acts and agreements are established in the 
[EU IR691/2010|Performance Regulation (691 / 2010)][law] and 
[Commission Implementing Regulation (EU) No 390 / 2013][law].


## Confidentiality

* The information is disseminated in accordance with Article 21 of the
  [Performance Regulation (691 / 2010)][law].
* The information is disseminated in accordance with Article 22 of 
  [Commission Implementing Regulation (EU) No 390 / 2013][law]. 


## Release policy

### Release calendar
Additional ASMA time is released monthly with yearly aggregates.

### Release calendar access
Not applicable.

### User access
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 


## Frequency of dissemination
Data is published monthly with the annual performance aggregate being available in January
of the following year. 


## Dissemination format
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 

## Accessibility of documentation

### Documentation on methodology
As per the pertaining regulations (see [Institutional Mandate](#institutional-mandate)).<br>
For technical questions not addressed in [Statistical processing](#statistical-processing)
please contact: [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int).<br>
Additional definitions of the terms used in the frame of the this [KPI][kpi]
are available in the [Metadata page](..).

### Quality documentation
There is no specific documentation on procedures applied for quality management
and quality assessment.


## Quality Management

### Quality assurance
Data validation is performed by the Central Office for Delay Analysis (CODA), on behalf of PRU, on each data delivery by airports,
and data validation report are returned to the data providers.

### Quality assessment

Raw data is cross-checked with various sources ([Network manager][nm-cfmu], ANSP's,
airport operators, airport coordinators and air carriers).
A quality threshold is established, and data that does not pass the quality threshold is rejected.

If a field is found to be blank, it is tried to fill the missing value from an alternative
data source (i.e. a missing aircraft type in the airport data flow can be filled
with information from the [Network manager][nm-cfmu].)


### Completeness

The data is collected for all airports subject to performance monitoring within
the SES performance scheme.
Data completeness is determined each month as per the above-mentioned quality checks.
Any missing data is reported to the provider. 



## Relevance

The information is published for performance monitoring purposes in accordance with
the relevant EU legislation. 

### Completeness
The data is collected for the entire [Single European Sky Area][ses-area].

## Accuracy and reliability

### Overall accuracy
The accuracy of the measure is influenced by the availability of the entry point/runway
configuration.


### Sampling error

There is no sampling and therefore no sampling error. 


## Timeliness and punctuality
### Timeliness
The information is published each month - in general around 30 days after the end
of the month in question.

###  Punctuality
The internal databases are updated daily. The [statistical processing](#statistical-processing)
is performed once per month.

## Comparability
### Comparability — geographical

The data is collected centrally by the [EUROCONTROL Performance Review Unit (PRU)][pru]
with delegation to the Central Office for Delay Analysis (CODA) and computed consistently for all airports
subject to performance monitoring within the SES performance scheme.

The interpretation of the measure and comparisons across airports require due consideration
of prevailing local circumstances (airport infrastructure, etc.) 



### Comparability over time
Comparisons over time are valid.

## Coherence
### Coherence — cross domain
Checks have been carried out with a number of airports and there is generally a good level
of coherence between the indicator results and the results from performance measurement systems
of airport operators. 


### Coherence — internal
Data is fully coherent from an internal perspective.



## Cost and burden

Not available. 


## Data revision

Subject to changes (i.e. airspace design), there might be a need to change
unimpeded times accordingly.

## Statistical processing

### Source data

In accordance with EU legislation, the data is collected centrally for all the airports
subject to performance monitoring within the SES performance scheme.

The input variables used for the calculation are detailed in the 
[Statistical concepts and definitions](#statistical-concepts-and-definitions) section. 


### Frequency of data collection
The data is collected on a daily basis and transmitted for statistical processing
on a monthly basis. 


### Data collection

The data is collected by the [EUROCONTROL Performance Review Unit (PRU)][pru] and the
Central Office for Delay Analysis (CODA).


### Data validation

The data is validation as described in the [Quality Management](#quality-management) section.


### Data compilation 

The ASMA area is defined as a 40-NM radius cylinder.

#### Calculation of the indicator

Let

* $c$, a combination of aircraft class, ASMA sectors and arrival runway,
  as described in the [Unimpeded ASMA time - Methodology][uasmamet],
* $f(c)$ a flight characterised by a combination $c$,
* $\mathrm{AcASMA}(f(c))$ the actual ASMA transit time for a flight $f(c)$,
  i.e. the elapsed time between the last entry of the flight $f(c)$ in its ASMA sector and
  its actual landing time (ALDT),
* $\mathrm{UASMA}(c)$ the [unimpeded ASMA time][uasma] for a combination $c$.

The additional ASMA time $\mathrm{AdASMA}(f(c))$ is calculated for each flight $f(c)$
as the difference between the actual ASMA transit time $\mathrm{AcASMA}(f(c))$
of the flight and the [unimpeded ASMA time][uasma] $\mathrm{UASMA}(c)$:
$$
 \mathrm{AdASAM}(f(c)) = \mathrm{AcASMA}(f(c)) - \mathrm{UASMA}(c)
$$

The additional ASMA time $\mathrm{AdASMA}(c)$ for a given combination $c$ is the average of
the additional ASMA time $\mathrm{AdASMA}(f(c))$ of all the flight $f(c)$ characterised by
that combination $c$.

The additional ASMA time $\mathrm{AdASMA}$ for a given airport is the weighted average
of the additional ASMA time $\mathrm{AdASMA}(c)$, for all the combinations $c$
at that airport with their probability of occurrence.


### Adjustment

Corrections may be made when issues are discovered as described in the
[Quality Assessment](#quality-assessment) section of this document. 


## Comment
No comments.

### Disclaimer {.disclaimer}

This data is published by the Performance Review Body (PRB) of the Single European Sky. Every effort has been made to ensure that the information and analysis contained on this website are as accurate and complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to the Performance Review Unit’s attention.

The information may be copied in whole or in part providing that the copyright notice and disclaimer are included. The information may not be modified without prior written permission from the PRB. The views expressed herein do not necessarily reflect the official views or policy of EUROCONTROL or of the European Commission, which make no warranty, either implied or express, for the information contained on this website, neither do they assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information. The PRB reserves the right to change or amend the information provided at any time and without prior notice. 


[uasma]: https://ansperformance.eu/definition/unimpeded-asma-time/ "Unimpeded ASMA Time"
[uasmamet]: https://ansperformance.eu/methodology/unimpeded-asma-time/ "Unimpeded ASMA Time - Methodology"
[ansp]: https://ansperformance.eu/acronym/ansp/ "ANSP"
[atfm-delay]: https://ansperformance.eu/definition/atfm-delay/ "ATFM Delay"
[air-stats]: https://ansperformance.eu/definition/air-transport-statistics/ "Air Transport Statistics"
[coda]: https://www.eurocontrol.int/articles/ir691-data-collection-process "CODA"
[ctot]: https://ansperformance.eu/acronym/ctot/ "CTOT"
[etot]: https://ansperformance.eu/acronym/etot/ "ETOT"
[fab]: https://ansperformance.eu/acronym/fab/ "FAB"
[fmp]: https://ansperformance.eu/acronym/fmp/ "FMP"
[kpi]: https://ansperformance.eu/acronym/kpi/ "KPI"
[ifr]: https://ansperformance.eu/acronym/ifr/ "IFR"
[law]: https://ansperformance.eu/bibliography/legislation/ "Legislation"
[nm-cfmu]: https://ansperformance.eu/acronym/nm-cfmu/ "NM"
[pru]: https://ansperformance.eu/about/us/ "PRU"
[refloc]: https://ansperformance.eu/definition/reference-location/ "Reference Location"
[regu]: https://ansperformance.eu/definition/regulation/ "Regulation"
[ses-area]: https://ansperformance.eu/definition/ses-area/ "SES Area"
[ses-portal]: https://www.eurocontrol.int/prudata/dashboard/ "SES Data Portal"

