---
title: ATC Pre-departure Delay
categories:
  - metadata
  - glossary
---

<style>
table, td {
  border: 1px solid #AAAAAA;
  border-collapse: collapse;
}
td {
  padding: 5px;
}
</style>

## Contacts

|||
|---------------------------|------------------------------------------------------------------------------------|
| Contact organisation      | EUROCONTROL: The European organisation for the safety of air navigation            |
| Contact organisation unit |	Directorate European Civil-Military Aviation - Performance Review Unit (DECMA/PRU) |
| Contact name              |	Performance Review Unit - EUROCONTROL                                              |
| Contact mail address      | 96 Rue de la Fusée<br>1130 Brussels<br>Belgium                                     |
| Contact e-mail address    | [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int)                  |

## Metadata update

|||
|-------------------------|-------------------|
| Metadata last certified | not applicable    |
| Metadata last update 	  | 01 November 2016  |


## Statistical presentation

### Data description

The **ATC pre-departure delay** is the additional time that the aircraft is held at the stand
to avoid queuing at the departure runway.
It is a proxy of the delay which an aircraft ready to leave its gate can be subject to,
at its origin airport, due to airports constraints, demand/capacity imbalances known prior
to off-blocks, take-off restrictions and/or traffic intensity at the time of operations.
It is however to be acknowledged that this indicator does not aim at filtering out
push-back delays when these are generated by an apron management unit which is not under
the control of the ANS provider.

As per the [Commission Implementing Regulation (EU) No 390 / 2013][law], Annex I, Section 2,
para 3.2, the ATC pre-departure delay is a performance indicator which will be collected for
performance monitoring only, at national level with a breakdown at airport level.
This performance indicator is further defined as follows:


* *"(i) the indicator is the average ATC pre-departure delay per outbound IFR flight;*
* *(ii) the indicator includes all IFR flights taking-off at the departure airport and
  covers delays in start up due to air traffic control constraints when the aircraft is ready
  to leave the departure stand;*
* *(iii) the indicator is calculated for the whole calendar year and for each year of
  the reference period.”*

As per [EU IR390 / 2013][law], Annex V, para 3.1.(u), the causes for ATC pre-departure delay
means the standard IATA delay codes as defined in Section F of the
Central Office for Delay Analysis (CODA) Digest Annual 2011
‘Delays to Air Transport in Europe’, with the duration of the delay.
These delay causes relate to IATA delay Code 89 that aims at capturing off-block delays due
to local ATC and push-back when the aircraft is ready to leave its stand.
More specifically, these codes aim at reporting restrictions at airport of departure,
including Air Traffic Services, start-up and pushback, airport and/or runway closed due
to obstruction or weather, industrial action, staff shortage, political unrest,
noise abatement, night curfew, special flights.

Where several causes may be attributable to flight delays, a list of those causes shall be provided.


### Classification system
ATC pre-departure delay is classified per Member State, with a breakdown for each airport subject to EU IR390.


### Sector coverage

The measures pertain to the [Air Transport and Air Traffic Management Sector][air-stats]
of the economy. 


### Statistical concepts and definitions

The **ATC pre-departure delay** is defined as the duration (in minutes) of delay as
reported under IATA Code 89. 


### Statistical unit
The statistical unit is the airport. Airport level data is also aggregated to States.

### Statistical population
The statistical population is the set of 'the 2nd reference period (RP2) airports'
subject [EU IR390 / 2013]][law], within the [Single European Sky Area][ses-area].

### Reference area

The reference area is the Single European Sky Area of RP2 (2015-2019). 


### Time coverage
2015 is the first year for which data is presented in the scope of RP2.

### Base period
Not applicable.


## Unit of Measure
The ATC pre-departure delay is measured in minutes per outbound IFR flight [min/departure]. 


## Reference period

As fixed by the [Performance Regulation (390 / 2013)][law], the second reference period (RP2)
for the performance scheme shall cover the calendar years 2015 to 2019 inclusive. 

## Institutional Mandate
Legal acts and agreements are established in the
[Commission Implementing Regulation (EU) No 390 / 2013][law].


## Confidentiality

The information is disseminated in accordance with Article 22 of 
[Commission Implementing Regulation (EU) No 390 / 2013][law]. 


## Release policy

### Release calendar
ATC pre-departure delay data is released monthly with yearly aggregates. 

### Release calendar access
Not applicable.

### User access
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 



## Frequency of dissemination
Data is published monthly with the annual performance aggregate being available in March
of the following year.


## Dissemination format
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 

## Accessibility of documentation

### Documentation on methodology
As per the pertaining regulations (see [Institutional Mandate](#institutional-mandate)).<br>
For technical questions not addressed in [Statistical processing](#statistical-processing)
please contact: [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int).<br>
Additional definitions of the terms used in the frame of the this [KPI][kpi]
are available in the [Metadata page](..).

### Quality documentation
There is no specific documentation on procedures applied for quality management
and quality assessment.



## Quality Management

As per [Performance Regulation (390 / 2013)][law], Article 21 (3), 

> The data providers shall take
> the necessary measures to ensure the quality, validation and timely transmission of the data,
> including providing evidence of their quality checks and validation processes, explanations
> in response to specific requests from the Commission regarding the quality of the data and,
> where necessary, action plans to improve data quality.
> The data shall be provided free of charge, in electronic form where applicable,
> using the format specified by the Commission.

The limitation of taxonomy and usage of IATA Code 89 has been acknowledged since many years.
As an example, it is currently impossible to detect late push-back approval issued by
an apron management body if it is not under ANS provider’s responsibility.

The use of IATA delay sub-codes significantly improves the reporting accuracy.
IATA delay sub-codes were introduced in the AHM731 (Airport Handling Manual) in 2011
and cater for more detailed reporting of ATC and reactionary delays.
These sub-codes are already in use at some airports such as Dusseldorf and London Luton.

Data accuracy varies considerably across airports and airlines depending on the procedures
which are in place to control the quality of Code 89 allocation.
As per Article 21 (3) referred to above, both airports and airlines are encouraged to
set up a clear process for appropriate allocation of Code 89 delay causes.

Although data providers are responsible for data quality, the EUROCONTROL
Performance Review Unit performs data validation and quality checks. 


### Quality assurance
Data validation is performed by the Central Office for Delay Analysis (CODA), on behalf of PRU, on each data delivery
by airports and airlines, and data validation report are returned to the data providers.

### Quality assessment

Raw data is cross-checked with various sources (CODA, ANSP's, airport operators,
airport coordinators and air carriers).
A threshold is established for data coverage,
and data that does not pass the quality threshold is rejected. 


## Relevance

The information is published for performance monitoring purposes in accordance
with Article 3 of the [Performance Regulation (EU) No 390 / 2013][law]. 



## Accuracy and reliability

### Overall accuracy
The accuracy of the measure is influenced by the availability and the reliability
of both the duration and the IATA codes as reported by local bodies. 


### Sampling error

There is no sampling and therefore no sampling error. 



## Timeliness and punctuality
### Timeliness

The information is published each month - in general around 30 days after
the end of the month in question.


###  Punctuality
The internal databases are updated daily. The [statistical processing](#statistical-processing)
is performed once per month.



## Comparability
### Comparability — geographical
The data is collected centrally by the [EUROCONTROL Performance Review Unit (PRU)][pru]
with delegation to the Central Office for Delay Analysis (CODA),
and computed consistently for all the RP2-airports.
The interpretation of the measure and comparisons across airports require
due consideration of prevailing local circumstances (airport infrastructure, etc.). 

### Comparability over time
Comparisons over time are valid.

## Coherence
### Coherence — cross domain
Checks have been carried out with a number of airports and there is generally
a good level of coherence between the indicator results and the results
from performance measurement systems of airport operators.

### Coherence — internal
Data is fully coherent from an internal perspective.

## Cost and burden

Not available. 


## Data revision

Subject to changes (i.e. review of IATA codes by the European Airport Punctuality Network Group,
EAPN), there might be a need to review ATC pre-departure delay accordingly.  




## Statistical processing

### Source data

In accordance with [Performance Regulation 390 / 2013][law], Annex IV,
the data is collected centrally for all the RP2-airports.

The input variables used for the calculation are detailed in the
[Statistical concepts and definitions](#statistical-concepts-and-definitions) section. 



### Frequency of data collection
The data is collected and transmitted for statistical processing on a monthly basis.


### Data collection

The data is collected by the [EUROCONTROL Performance Review Unit (PRU)][pru] and
the Central Office for Delay Analysis (CODA). 


### Data validation

The data is validation as described in the [Quality Management](#quality-management) section.


### Data compilation 

ATC pre-departure delay is reported as provided by local bodies. There is no specific compilation. 

### Adjustment
Corrections may be made when issues are discovered as described in the
[Quality Assessment section of this document](#quality-assessment).



## Comment
No comments.

### Disclaimer {.disclaimer}

This data is published by the Performance Review Body (PRB) of the Single European Sky. Every effort has been made to ensure that the information and analysis contained on this website are as accurate and complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to the Performance Review Unit’s attention.

The information may be copied in whole or in part providing that the copyright notice and disclaimer are included. The information may not be modified without prior written permission from the PRB. The views expressed herein do not necessarily reflect the official views or policy of EUROCONTROL or of the European Commission, which make no warranty, either implied or express, for the information contained on this website, neither do they assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information. The PRB reserves the right to change or amend the information provided at any time and without prior notice. 



[air-stats]: https://ansperformance.eu/definition/air-transport-statistics/ "Air Transport Statistics"
[atfm-delay]: https://ansperformance.eu/definition/atfm-delay/ "ATFM Delay"
[ctot]: https://ansperformance.eu/acronym/ctot/ "CTOT"
[etot]: https://ansperformance.eu/acronym/etot/ "ETOT"
[fab]: https://ansperformance.eu/acronym/fab/ "FAB"
[fir]: https://ansperformance.eu/acronym/fir/ "FIR"
[fmp]: https://ansperformance.eu/acronym/fmp/ "FMP"
[kpi]: https://ansperformance.eu/acronym/kpi/ "KPI"
[ifr]: https://ansperformance.eu/acronym/ifr/ "IFR"
[law]: https://ansperformance.eu/bibliography/legislation/ "Legislation"
[nm-cfmu]: https://ansperformance.eu/acronym/nm-cfmu/ "NM"
[nm20]: https://ansperformance.eu/library/NM_20_FB750_Delay_Calculation_improvements.pdf "REA Message"
[pru]: https://ansperformance.eu/about/us/ "PRU"
[refloc]: https://ansperformance.eu/definition/reference-location/ "Reference Location"
[regu]: https://ansperformance.eu/definition/regulation/ "Regulation"
[ses-area]: https://ansperformance.eu/definition/ses-area/ "SES Area"
[ses-portal]: https://www.eurocontrol.int/prudata/dashboard/ "SES Data Portal"
