---
title: ATFM Slot Adherence
categories:
  - metadata
  - glossary
---

<style>
table, td {
  border: 1px solid #AAAAAA;
  border-collapse: collapse;
}
td {
  padding: 5px;
}
</style>

## Contacts

|||
|---------------------------|------------------------------------------------------------------------------------|
| Contact organisation      | EUROCONTROL: The European organisation for the safety of air navigation            |
| Contact organisation unit |	Directorate European Civil-Military Aviation - Performance Review Unit (DECMA/PRU) |
| Contact name              |	Performance Review Unit - EUROCONTROL                                              |
| Contact mail address      | 96 Rue de la Fusée<br>1130 Brussels<br>Belgium                                     |
| Contact e-mail address    | [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int)                  |

## Metadata update

|||
|-------------------------|-------------------|
| Metadata last certified | not applicable    |
| Metadata last update 	  | 01 November 2016  |


## Statistical presentation

### Data description

ATFM departure slots are allocated centrally by the European Network Manager upon the request
of the local Flow Management Position (FMP), when an imbalance between demand and capacity is
foreseen at airports and/or en-route.
The purpose of such regulation is to hold aircraft on the ground.

An ATFM slot tolerance window is available to ATC to sequence departures.
The standard slot tolerance window is [-5 minutes, +10 minutes].
ATC at the departure airport has a joint responsibility with aircraft operators to ensure that
flights departure within the allocated ATFM slot tolerance window in order to optimise traffic flow.
ATFM departure slot adherence, simply named **ATFM slot adherence** hereafter,
measures the share of take-offs inside the slot tolerance window of [-5 minutes, +10 minutes].

ATFM slot adherence monitoring is a pre-requisite to fine tune traffic predictions
at the departure, en-route airspace and at the destination airports.
The higher the number of regulated departing aircraft inside the assigned ATFM standard window,
the more accurate the predicted traffic and associated down-stream ATFM measures. 


ATFM slot adherence monitoring is required by the [Regulation (EU) No 255 / 2010][law].
Under Article 11 of this regulation, the ATS units are required to provide the information
regarding non-compliance to slot adherence for these airports where non-adherence equals
or exceeds 20% of the regulated departures, as well as their action plans to mitigate such
a non-compliance.

In application to Regulation (EU) No 255/2010, the Network Manager monitors ATFM slot adherence
on a monthly basis.

The [Performance Regulation (390 / 2013)][law], Annex I Section 2 para 3.2(a) also requires
ATFM slot adherence to be monitored at local level, i.e. at national level with a breakdown
at airport level. 


### Classification system

ATFM slot adherence is classified per Member State, with a breakdown for each airport subject to EU IR390.


### Sector coverage

The measures pertain to the [Air Transport and Air Traffic Management Sector][air-stats]
of the economy. 


### Statistical concepts and definitions

**ATFM slot adherence** is defined as the percentage of departures inside an
ATFM slot tolerance window of [-5 minutes, +10 minutes]. 


### Statistical unit
The statistical unit is the airport. Airport level data is also aggregated to States.

### Statistical population
The statistical population is the set of 'the 2nd reference period (RP2) airports'
subject [EU IR390 / 2013]][law], within the [Single European Sky Area][ses-area].

### Reference area

The reference area is the Single European Sky Area of RP2 (2015-2019). 


### Time coverage

The Network manager has monitored slot adherence to ATFM since 2011,
but in the scope of the Performance Scheme, 2015 is the first year for which data is presented.


### Base period
Not applicable.


## Unit of Measure
The ATC pre-departure delay is measured in minutes per outbound IFR flight [min/departure]. 


## Reference period

As fixed by the [Performance Regulation (390 / 2013)][law], the second reference period (RP2)
for the performance scheme shall cover the calendar years 2015 to 2019 inclusive. 

## Institutional Mandate
Legal acts and agreements are established in the
[Commission Implementing Regulation (EU) No 390 / 2013][law].


## Confidentiality

The information is disseminated in accordance with Article 21 of 
[Commission Implementing Regulation (EU) No 390 / 2013][law]. 


## Release policy

### Release calendar
ATFM slot adherence is released monthly with yearly aggregates. 

### Release calendar access
Not applicable.

### User access
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 



## Frequency of dissemination
Data is published monthly with the annual performance aggregate being available in January
of the following year.


## Dissemination format
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 

## Accessibility of documentation

### Documentation on methodology
As per the pertaining regulations (see [Institutional Mandate](#institutional-mandate)).<br>
For technical questions not addressed in [Statistical processing](#statistical-processing)
please contact: [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int).<br>
Additional definitions of the terms used in the frame of the this [KPI][kpi]
are available in the [Metadata page](..).

### Quality documentation
There is no specific documentation on procedures applied for quality management
and quality assessment.



## Quality Management

As per [Performance Regulation (390 / 2013)][law], Article 21 (3), 

> The data providers shall take
> the necessary measures to ensure the quality, validation and timely transmission of the data,
> including providing evidence of their quality checks and validation processes, explanations
> in response to specific requests from the Commission regarding the quality of the data and,
> where necessary, action plans to improve data quality.
> The data shall be provided free of charge, in electronic form where applicable,
> using the format specified by the Commission.



### Quality assurance

Data validation is performed by the [Network manager][nm-cfmu] in the the
[Regulation (EU) No 255 / 2010][law].

### Quality assessment

Quality assessment is under the responsibility of the [Network manager][nm-cfmu]
in the context of the [Regulation (EU) No 255 / 2010][law]. 

### Completeness

The data is collected for all the RP2-airports.


## Relevance

The information is published for performance monitoring purposes in accordance
with Article 3 of the [Performance Regulation (EU) No 390 / 2013][law]. 



## Accuracy and reliability

### Overall accuracy
The information is published for performance monitoring purposes in accordance with
Article 3 of the [Performance Regulation (EU) No 390 / 2013][law]. 

### Sampling error

There is no sampling and therefore no sampling error. 



## Timeliness and punctuality
### Timeliness

The information is published each month by the Network Manager in their
“NM Monthly Adherence to ATFCM Slots” bulletin. 


###  Punctuality
The internal databases are updated daily. The [statistical processing](#statistical-processing)
is performed once per month.



## Comparability
### Comparability — geographical
The data is collected centrally by the [Network Manager][nm-cfmu], as required by the
[Regulation (EU) No 255 / 2010][law].
In the scope of the [Performance Regulation (390 / 2013)][law], the data is transmitted to
the EUROCONTROL Performance Review Unit and computed consistently for all the EU IR390 airports. 

### Comparability over time
Comparisons over time are valid.

## Coherence
### Coherence — cross domain
Not available.

### Coherence — internal
Data is fully coherent from an internal perspective.

## Cost and burden

Not available. 


## Data revision

No data revision foreseen.




## Statistical processing

### Source data

The input variables used for the calculation are detailed in the
[Statistical concepts and definitions](#statistical-concepts-and-definitions) section. 



### Frequency of data collection
The data is collected and transmitted for statistical processing on a monthly basis.


### Data collection

The data is collected by the [Network Manager][nm-cfmu] for the purpose of
[Regulation (EU) No 255 / 2010][law] and transmitted to the EUROCONTROL Performance Review Unit
for the implementation of the [Performance Regulation (390 / 2013)][law]. 


### Data validation

The data is validation as described in the [Quality Management](#quality-management) section.


### Data compilation 

The departure time of a regulated flight is inside the slot tolerance window when its
Actual Take-off time (ATOT) is in a window starting 5 minutes before and ending 10 minutes after
its Calculated Take-Off time (CTOT), i.e.

$$CTOT – 5 min <= ATOT <= CTOT + 10 min $$

It should be acknowledged that the exceptional extension of the standard
ATFM slot tolerance window [-5 minutes, +10 minutes], as described in the ATFCM User Manual
under 4.6.4 “Adverse Operating Conditions at Aerodromes”, is not taken into account in the
calculation of ATFM slot adherence.
These exceptions represent in most cases less than 2% of regulated flights.

The adherence to ATFM slots determines the percentage of regulated flights with an ATOT
inside the slot tolerance window.

The Actual Take-Off time of a flight can be determined when the NM received
an ATC activation message from its departure airport.
Therefore, the assessment is made only for those flights for which an activation message
at the origin airport (FSA message) or a Departure message (DEP) is available. 



### Adjustment
Corrections may be made when issues are discovered as described in the
[Quality Assessment section of this document](#quality-assessment).



## Comment
No comments.

### Disclaimer {.disclaimer}

This data is published by the Performance Review Body (PRB) of the Single European Sky. Every effort has been made to ensure that the information and analysis contained on this website are as accurate and complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to the Performance Review Unit’s attention.

The information may be copied in whole or in part providing that the copyright notice and disclaimer are included. The information may not be modified without prior written permission from the PRB. The views expressed herein do not necessarily reflect the official views or policy of EUROCONTROL or of the European Commission, which make no warranty, either implied or express, for the information contained on this website, neither do they assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information. The PRB reserves the right to change or amend the information provided at any time and without prior notice. 


[air-stats]: https://ansperformance.eu/definition/air-transport-statistics/ "Air Transport Statistics"
[ansp]: https://ansperformance.eu/acronym/ansp/ "ANSP"
[atfm-delay]: https://ansperformance.eu/definition/atfm-delay/ "ATFM Delay"
[ctot]: https://ansperformance.eu/acronym/ctot/ "CTOT"
[etot]: https://ansperformance.eu/acronym/etot/ "ETOT"
[fab]: https://ansperformance.eu/acronym/fab/ "FAB"
[fir]: https://ansperformance.eu/acronym/fir/ "FIR"
[fmp]: https://ansperformance.eu/acronym/fmp/ "FMP"
[kpi]: https://ansperformance.eu/acronym/kpi/ "KPI"
[ifr]: https://ansperformance.eu/acronym/ifr/ "IFR"
[law]: https://ansperformance.eu/bibliography/legislation/ "Legislation"
[nm-cfmu]: https://ansperformance.eu/acronym/nm-cfmu/ "NM"
[nm20]: https://ansperformance.eu/library/NM_20_FB750_Delay_Calculation_improvements.pdf "REA Message"
[pru]: https://ansperformance.eu/about/us/ "PRU"
[refloc]: https://ansperformance.eu/definition/reference-location/ "Reference Location"
[regu]: https://ansperformance.eu/definition/regulation/ "Regulation"
[ses-area]: https://ansperformance.eu/definition/ses-area/ "SES Area"
[ses-portal]: https://www.eurocontrol.int/prudata/dashboard/ "SES Data Portal"
