---
title: Average Horizontal En-route Inefficiency
categories:
  - metadata
  - glossary
---

<style>
table, td {
  border: 1px solid #AAAAAA;
  border-collapse: collapse;
}
td {
  padding: 5px;
}
</style>

## Contacts

|||
|---------------------------|------------------------------------------------------------------------------------|
| Contact organisation      | EUROCONTROL: The European organisation for the safety of air navigation            |
| Contact organisation unit |	Directorate European Civil-Military Aviation - Performance Review Unit (DECMA/PRU) |
| Contact name              |	Performance Review Unit - EUROCONTROL                                              |
| Contact mail address      | 96 Rue de la Fusée<br>1130 Brussels<br>Belgium                                     |
| Contact e-mail address    | [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int)                  |

## Metadata update

|||
|-------------------------|-------------------|
| Metadata last certified | not applicable    |
| Metadata last update 	  | 01 November 2016  |


## Statistical presentation

### Data description

The measure provides an indication of the flight efficiency en route.

The **Average Horizontal En-route Flight Efficiency** indicator compares the length of the
en-route part of flight trajectories with a corresponding portion of the [Great Circle][gcd]
(defined with respect to the [reference area][#reference-area]).
‘En-route’ is defined as the distance flown outside a circle of 40 NM around the airport.

In the first reference period (2012-14) the calculation of the KPI is based on the
[Filed Tactical Flight Model (FTFM)][ftfm] which corresponds to the last filed flight plan
(see also [Horizontal flight efficiency calculations][hfe-meth]).  


### Classification system

Average horizontal en route inefficiency is calculated for the [reference area](#reference-area).

Complementary to the EU-wide KPI, a number of additional
[Horizontal flight efficiency calculations][hfe-meth] are carried out for monitoring purposes. 

### Sector coverage

The measures pertain to the [Air Transport and Air Traffic Management Sector][air-stats]
of the economy. 


### Statistical concepts and definitions

Of interest for the calculation are the [Great Circle][gcd] [reference area](#reference-area)
end-points (referred to as onset and terminus) and the couple(s) of entry/exit points in the
[measured area](#statistical-unit) of the en-route portion of the flight model
(i.e., excluding a 40 NM circle around the airports).
More details are provided in [Horizontal flight efficiency calculations][hfe-meth]. 


### Statistical unit
The statistical unit is a geographical area. 

### Statistical population
The statistical population comprises only one geographic area in RP1: the [Single European Sky Area][ses-area].
In RP2 it includes units at the local level (e.g., FABs). 


### Reference area

The reference area is the [Single European Sky Area][ses-area]. 


### Time coverage

Data is available from 2011.

### Base period
Not applicable.


## Unit of Measure
The KPI is presented as a percentage.

## Reference period

* The first reference period (RP1) covers the calendar years 2012 to 2014 inclusive.
* The second reference period (RP2) covers the calendar years 2015 to 2019 inclusive. 

Unless decided otherwise, the following reference periods shall be of five calendar years.


## Institutional Mandate
Legal acts and agreements are established in the
[Performance Regulation (691 / 2010)][law] and 
[Commission Implementing Regulation (EU) No 390 / 2013][law].


## Confidentiality

* The information is disseminated in accordance with Article 21 of the
  [Performance Regulation (691 / 2010)][law].
* The information is disseminated in accordance with Article 22 of the 
  [Commission Implementing Regulation (EU) No 390 / 2013][law]. 




## Release policy

### Release calendar
The indicator values are released monthly. 

### Release calendar access
Not applicable.

### User access
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 



## Frequency of dissemination
Data is published monthly with the annual performance aggregate being available in January
of the following year.


## Dissemination format
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 

## Accessibility of documentation

### Documentation on methodology
As per the pertaining regulations (see [Institutional Mandate](#institutional-mandate)).<br>
For technical questions not addressed in [Statistical processing](#statistical-processing)
please contact: [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int).<br>
Additional definitions of the terms used in the frame of the this [KPI][kpi]
are available in the [Metadata page](..).

### Quality documentation
There is no specific documentation on procedures applied for quality management
and quality assessment.



## Quality Management


### Quality assurance

The data is provided by the [Network Manager][nm-cfmu] and as such it is their
responsibility to perform any quality assurance activities.

EUROCONTROL is not responsible for the procedures and processes used in the production of this data. 


### Quality assessment

Data is validated by random quality checks, e.g. missing data for given a day, adherent data, etc.
Any issues are reported to the [Network manager][nm-cfmu] who works with the EUROCONTROL
Performance Review Unit to resolve them. 

### Completeness

It is assumed that the [Network Manager][nm-cfmu] provides complete data for the entire
[Single European Sky Area][ses-area].


## Relevance

The information is published for performance monitoring purposes in accordance with the
relevant EU legislation. 



## Accuracy and reliability

### Overall accuracy
This data is provided by the Network manager and apart from the basic consistency checks,
it is assumed that the data is accurate.  


### Sampling error
There is no sampling and therefore no sampling error. 



## Timeliness and punctuality
### Timeliness

The data is published each month - in general between 14 and 16 days after
the end of the month in question.  


###  Punctuality
To be determined.



## Comparability
### Comparability — geographical
Not applicable: there is only one reference area. 

### Comparability over time
It is assumed that this highly aggregated indicator will remain comparable over time.

## Coherence
### Coherence — cross domain
Generally, data should be similar to flight efficiency data published in other sources.

### Coherence — internal
The data is assumed to be internally coherent as provided. 

## Cost and burden

Not available. 


## Data revision

The data revision policy has not yet been defined.




## Statistical processing

### Source data

The source data is provided by the [Network Manager][nm-cfmu] and is processed by EUROCONTROL. 



### Frequency of data collection
The data is collected daily.



### Data collection

The [Network Manager][nm-cfmu] provides information concerning several different
Flight models and their intersections with airspaces of interest, such as the TMA areas
around the airports and the FIRs. 


### Data validation

The data is validation as described in the [Quality Management](#quality-management) section.


### Data compilation 

Computation of the en route section and the quantities needed for the computation of the KPI are
performed at EUROCONTROL and stored in a local database.

The calculation of the KPI in the 1st reference period (2012-14) is based on the
[Filed Tactical Flight Model (FTFM)][ftfm] which corresponds to the last filed flight plan
(see also [Horizontal flight efficiency calculations][hfe-meth]). 




### Adjustment
No adjustments are performed on this data, although invalid data elements are rejected.



## Comment
No comments.

### Disclaimer {.disclaimer}

This data is published by the Performance Review Body (PRB) of the Single European Sky. Every effort has been made to ensure that the information and analysis contained on this website are as accurate and complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to the Performance Review Unit’s attention.

The information may be copied in whole or in part providing that the copyright notice and disclaimer are included. The information may not be modified without prior written permission from the PRB. The views expressed herein do not necessarily reflect the official views or policy of EUROCONTROL or of the European Commission, which make no warranty, either implied or express, for the information contained on this website, neither do they assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information. The PRB reserves the right to change or amend the information provided at any time and without prior notice. 


[air-stats]: https://ansperformance.eu/definition/air-transport-statistics/ "Air Transport Statistics"
[ansp]: https://ansperformance.eu/acronym/ansp/ "ANSP"
[atfm-delay]: https://ansperformance.eu/definition/atfm-delay/ "ATFM Delay"
[coda]: https://www.eurocontrol.int/articles/central-office-delay-analysis-coda "CODA"
[ctot]: https://ansperformance.eu/acronym/ctot/ "CTOT"
[etot]: https://ansperformance.eu/acronym/etot/ "ETOT"
[fab]: https://ansperformance.eu/acronym/fab/ "FAB"
[fir]: https://ansperformance.eu/acronym/fir/ "FIR"
[fmp]: https://ansperformance.eu/acronym/fmp/ "FMP"
[ftfm]: https://ansperformance.eu/acronym/ftfm/ "FTFM"
[gcd]:https://ansperformance.eu/acronym/gcd/ "Great Circle Distance"
[kpi]: https://ansperformance.eu/acronym/kpi/ "KPI"
[hfe-meth]: https://ansperformance.eu/methodology/horizontal-flight-efficiency-pi/ "HFE Methodology"
[ifr]: https://ansperformance.eu/acronym/ifr/ "IFR"
[law]: https://ansperformance.eu/bibliography/legislation/ "Legislation"
[nm-cfmu]: https://ansperformance.eu/acronym/nm-cfmu/ "NM"
[nm20]: https://ansperformance.eu/library/NM_20_FB750_Delay_Calculation_improvements.pdf "REA Message"
[pru]: https://ansperformance.eu/about/us/ "PRU"
[refloc]: https://ansperformance.eu/definition/reference-location/ "Reference Location"
[regu]: https://ansperformance.eu/definition/regulation/ "Regulation"
[ses-area]: https://ansperformance.eu/definition/ses-area/ "SES Area"
[ses-portal]: https://www.eurocontrol.int/prudata/dashboard/ "SES Data Portal"