---
title: Terminal air navigation service costs and unit rates
categories:
  - metadata
  - glossary
---

<style>
table, td {
  border: 1px solid #AAAAAA;
  border-collapse: collapse;
}
td {
  padding: 5px;
}
</style>

## Contacts

|||
|---------------------------|------------------------------------------------------------------------------------|
| Contact organisation      | EUROCONTROL: The European organisation for the safety of air navigation            |
| Contact organisation unit |	Directorate European Civil-Military Aviation - Performance Review Unit (DECMA/PRU) |
| Contact name              |	Performance Review Unit - EUROCONTROL                                              |
| Contact mail address      | 96 Rue de la Fusée<br>1130 Brussels<br>Belgium                                     |
| Contact e-mail address    | [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int)                  |

## Metadata update

|||
|-------------------------|-------------------|
| Metadata last certified | not applicable    |
| Metadata last update 	  | 01 November 2016  |


## Statistical presentation

### Data description

The measure addresses the costs for the provision of terminal air navigation services.

The European Commission is required to collect, consolidate and monitor [Terminal ANS Costs][tcost]
and [Terminal ANS Unit Rate][trate] by the [EU Performance Regulation (EU IR691 / 2010)][law] and
in accordance with [ EC Charging Scheme (EC 1794 / 2006)][law]. 

The [EC Charging Scheme (EC 1794 / 2006)][law] for air navigation services contributes
to greater transparency in the determination, imposition and enforcement of charges
to airspace users and also contributes to the cost efficiency of providing air navigation services
and to efficiency of flights, while maintaining an optimum safety level. 

The cost of air navigation services comprise for the most part, two elements:

* en-route costs,
* terminal costs.

The cost of terminal services is related to the following services:

* airport control services, airport flight information services including
  air traffic advisory services, and alerting services;
* air traffic services related to the approach and departure of aircraft within
  a certain distance of an airport on the basis of operational requirements;
* an appropriate allocation of all other air navigation services components,
  reflecting a proportionate attribution between en-route and terminal services.

The concepts of terminal ANS costs and unit rates are linked by the [charges][tcharge]
paid by airspace users.
These charges are equal to the total number of service units multiplied by the terminal unit rate.


### Classification system

Terminal air navigation services costs and unit rates are classified per
[Terminal Charging Zone][csdefs] within the [Single European Sky Area][ses-area].

Each Terminal Charging Zone belongs to a single State in the zone.



### Sector coverage

The measures pertain to the [Air Transport and Air Traffic Management Sector][air-stats]
of the economy. 


### Statistical concepts and definitions

All cost values are expressed as:

* Euro or National currencies outside the Euro area,
* costs in [Real terms][reaterms],
* costs in [Nominal terms][nomterms].


### Statistical unit
The statistical unit is the 
[Terminal Charging Zone][csdefs].

### Statistical population
The statistical population comprises the [Terminal Charging Zone][csdefs]s the
[Single European Sky Area][ses-area].


### Reference area

The reference area is the [Single European Sky Area][ses-area]. 


### Time coverage

Actual Costs are measured over the period 2012 to the year before the current year. 

### Base period
2009 is the base year for the calculation of cost series in [Real terms][reaterms].

## Unit of Measure
Costs and unit rates are measured in:

* Local currency in [nominal terms][nomterms],
* Local currency in [real terms][reaterms], 
* EUR in [real terms][reaterms].

Real terms values are corrected for inflation relative to the [base year](#base-period).

## Reference period

* The first reference period (RP1) covers the calendar years 2012 to 2014 inclusive.
* The second reference period (RP2) covers the calendar years 2015 to 2019 inclusive. 

Unless decided otherwise, the following reference periods shall be of five calendar years.


## Institutional Mandate
Legal acts and agreements are established in the
[Performance Regulation (691 / 2010)][law] and the
[Charging Regulation (1794 / 2006)][law].


## Confidentiality

* The information is disseminated in accordance with Article 21 of the
  [Performance Regulation (691 / 2010)][law].
* The information is disseminated in accordance with Article 22 of the 
  [Commission Implementing Regulation (EU) No 390 / 2013][law]. 




## Release policy

### Release calendar
The Terminal ANS costs and unit rates are released twice a year.  

### Release calendar access
Not applicable.

### User access
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 



## Frequency of dissemination
The Terminal ANS costs and unit rates are published on a yearly basis. 


## Dissemination format
Information is disseminated to the general public via the [SES Data Portal][ses-portal]. 

## Accessibility of documentation

### Documentation on methodology
As per the pertaining regulations (see [Institutional Mandate](#institutional-mandate)).<br>
For technical questions not addressed in [Statistical processing](#statistical-processing)
please contact: [PRU-Support@eurocontrol.int](mailto:PRU-Support@eurocontrol.int).<br>
Additional definitions of the terms used in the frame of the this [KPI][kpi]
are available in the [Metadata page](..).

### Quality documentation
There is no specific documentation on procedures applied for quality management
and quality assessment.



## Quality Management


### Quality assurance

The data is provided by the concerned States and as such it is their responsibility
to perform any quality assurance activities. 

EUROCONTROL is not responsible for the procedures and processes used in the production of this data. 


### Quality assessment

EUROCONTROL performs systematic checks to verify that totals do indeed equal the sum of their parts.
However, if discrepancies are found, they are simply reported to data provider who may or may
not make corrections.

EUROCONTROL does not change data elements nor does it prevent the publication of data that
failed to verify the checks.


## Relevance

The information is published for performance monitoring purposes in accordance with the
relevant EU legislation. 



## Accuracy and reliability

### Overall accuracy
This data is provided by the States and displayed as provided.
It is assumed that the States have provided perfectly accurate data. 

### Sampling error
There is no sampling and therefore no sampling error. 



## Timeliness and punctuality
### Timeliness

The latest data displayed represents costs and rates that are at least eleven months old.  


###  Punctuality
The data is provided by the States in June and November and is displayed to the public at
the end of November. 



## Comparability
### Comparability — geographical
Depending on the State, [terminal charging zone][csdefs]s may include from one to more
than sixty airports, which would tend to reduce the validity of geographical comparison.

### Comparability over time
The exact composition of a given [terminal charging zone][csdefs] may vary over time,
e.g. changes in the number of airports concerned, which would tend to reduce the
comparability over time. 



## Coherence
### Coherence — cross domain
Generally, data should be coherent with ATM Cost-effectiveness (ACE) information.

### Coherence — internal
The data is assumed to be internally coherent as provided. 

## Cost and burden

Not available. 


## Data revision

The data revision policy has not yet been defined.




## Statistical processing

### Source data

#### Forecast Data

**Terminal ANS costs and related data**
: National/[FAB] performance plans adopted by the States for the first [reference period][csdefs].

**Exchange rates (2009)**
: National/[FAB] performance plans adopted by the States for the first [reference period][csdefs].

**Inflation rates**
: Forecast data: National/[FAB] performance plans adopted by the States for the first [reference period][csdefs]. 



### Frequency of data collection
The data is collected twice a year (June & November).



### Data collection

Air navigation service providers are required to fill a reporting table for each terminal
charging zone under their responsibility and supply it to the 
European Commission ([Charging Regulation (EC 1794 / 2006)][law]). 


### Data validation
The data is validated by the States/data providers under their own responsibility. 


### Data compilation 

The data provided is loaded into a database at EUROCONTROL but no aggregation or
modification is performed. 




### Adjustment
No adjustments are performed on this data.



## Comment
No comments.

### Disclaimer {.disclaimer}

This data is published by the Performance Review Body (PRB) of the Single European Sky. Every effort has been made to ensure that the information and analysis contained on this website are as accurate and complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you could please bring them to the Performance Review Unit’s attention.

The information may be copied in whole or in part providing that the copyright notice and disclaimer are included. The information may not be modified without prior written permission from the PRB. The views expressed herein do not necessarily reflect the official views or policy of EUROCONTROL or of the European Commission, which make no warranty, either implied or express, for the information contained on this website, neither do they assume any legal liability or responsibility for the accuracy, completeness or usefulness of this information. The PRB reserves the right to change or amend the information provided at any time and without prior notice. 


[air-stats]: https://ansperformance.eu/definition/air-transport-statistics/ "Air Transport Statistics"
[ansp]: https://ansperformance.eu/acronym/ansp/ "ANSP"
[ansp-ses-rp1]: ..//ansp-ses-rp1/ "ANSPs - SES RP1"
[atfm-delay]: https://ansperformance.eu/definition/atfm-delay/ "ATFM Delay"
[csdefs]: ../charging-scheme-regulation-article-2-definitions/ "Charging Scheme Regulation Article 2 definitions"
[coda]: https://www.eurocontrol.int/articles/central-office-delay-analysis-coda "CODA"
[ctot]: https://ansperformance.eu/acronym/ctot/ "CTOT"
[etot]: https://ansperformance.eu/acronym/etot/ "ETOT"
[fab]: https://ansperformance.eu/acronym/fab/ "FAB"
[fir]: https://ansperformance.eu/acronym/fir/ "FIR"
[fmp]: https://ansperformance.eu/acronym/fmp/ "FMP"
[ftfm]: https://ansperformance.eu/acronym/ftfm/ "FTFM"
[gcd]:https://ansperformance.eu/acronym/gcd/ "Great Circle Distance"
[kpi]: https://ansperformance.eu/acronym/kpi/ "KPI"
[hfe-meth]: https://ansperformance.eu/methodology/horizontal-flight-efficiency-pi/ "HFE Methodology"
[ifr]: https://ansperformance.eu/acronym/ifr/ "IFR"
[law]: https://ansperformance.eu/bibliography/legislation/ "Legislation"
[nm-cfmu]: https://ansperformance.eu/acronym/nm-cfmu/ "NM"
[nm20]: https://ansperformance.eu/library/NM_20_FB750_Delay_Calculation_improvements.pdf "REA Message"
[nomterms]: ../nominal-terms/ "Nominal terms"
[pru]: https://ansperformance.eu/about/us/ "PRU"
[refloc]: https://ansperformance.eu/definition/reference-location/ "Reference Location"
[regu]: https://ansperformance.eu/definition/regulation/ "Regulation"
[reaterms]: ../real-terms/ "Real terms"
[ses-area]: https://ansperformance.eu/definition/ses-area/ "SES Area"
[ses-portal]: ../../ "SES Data Portal"
[tcost]: ../terminal-ans-costs/ "Terminal ANS Costs"
[trate]: https://ansperformance.eu/definition/terminal-ans-unit-rate/ "Terminal ANS Unit Rate"
[tcharge]: ../terminal-ans-costs/ "Terminal ANS Unit Rate"

