---
title: Data Download

dwnld_i: <i class="fa pru fa-download"></i>
info_i: <i class="fa pru fa-info-circle"></i>
ndwk_i: <i class="fa pru fa-flask"></i>
fltr_i: <i class="fa pru fa-filter"></i>
attn_i: <i class="fa pru fa-exclamation-triangle"></i>

---

## 2024 (post operational adjustments are not yet taken into account)
  
| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Share of arrivals applying CDO        | [{{% dwnld_i %}} RP3_APT_CDO_2024_Jan_May.xlsx][RP3_CCO_CDO_2024]             |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP3_APT_ATC_PRE_2024_Jan_May.xlsx][RP3_APT_ATC_PRE_2024]         |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP3_APT_ATFM_ARR_2024_Jan_Jun.xlsx][RP3_APT_ATFM_ARR_2024]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP3_APT_ATFM_SLOT_2024_Jan_Jun.xlsx][RP3_APT_ATFM_SLOT_2024] |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP3_ERT_ATFM_2024_Jan_Jun.xlsx][RP3_ERT_ATFM_2024]           |
| En-route Service Units                | [{{% dwnld_i %}} RP3_ERT_SU_2024_Jan_May.xlsx][RP3_ERT_SU_2024]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP3_Flights_2024_Jan_Jun.xlsx][RP3_Flights_2024]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP3_FLT_EFF_2024_Jan_Jun.xlsx][RP3_FLT_EFF_2024]             |          |
           |

[RP3_APT_ATC_PRE_2024]:   ../download/2024/RP3_APT_ATC_PRE_2024_Jan_May.xlsx
[RP3_APT_ATFM_ARR_2024]:  ../download/2024/RP3_APT_ATFM_ARR_2024_Jan_Jun.xlsx
[RP3_APT_ATFM_SLOT_2024]: ../download/2024/RP3_APT_ATFM_SLOT_2024_Jan_Jun.xlsx
[RP3_ERT_ATFM_2024]:      ../download/2024/RP3_ERT_ATFM_2024_Jan_Jun.xlsx
[RP3_ERT_SU_2024]:        ../download/2024/RP3_ERT_SU_2024_Jan_May.xlsx
[RP3_Flights_2024]:       ../download/2024/RP3_Flights_2024_Jan_Jun.xlsx
[RP3_FLT_EFF_2024]:       ../download/2024/RP3_FLT_EFF_2024_Jan_Jun.xlsx
[RP3_CCO_CDO_2024]:       ../download/2024/RP3_APT_CDO_2024_Jan_May.xlsx


## 2023
  
| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP3_APT_ASMA_2023_Jan_Dec.xlsx][RP3_APT_ASMA_2023]             |
| Share of arrivals applying CDO        | [{{% dwnld_i %}} RP3_APT_CDO_2023_Jan_Dec.xlsx][RP3_CCO_CDO_2023]             |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP3_APT_ATC_PRE_2023_Jan_Dec.xlsx][RP3_APT_ATC_PRE_2023]         |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP3_APT_ATFM_ARR_2023_Jan_Dec.xlsx][RP3_APT_ATFM_ARR_2023]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP3_APT_ATFM_SLOT_2023_Jan_Dec.xlsx][RP3_APT_ATFM_SLOT_2023] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP3_APT_TxOut_2023_Jan_Dec.xlsx][RP3_APT_TxOut_2023]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP3_ERT_ATFM_2023_Jan_Dec.xlsx][RP3_ERT_ATFM_2023]           |
| En-route Service Units                | [{{% dwnld_i %}} RP3_ERT_SU_2023_Jan_Dec.xlsx][RP3_ERT_SU_2023]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP3_Flights_2023_Jan_Dec.xlsx][RP3_Flights_2023]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP3_FLT_EFF_2023_Jan_Dec.xlsx][RP3_FLT_EFF_2023]             |          |
           |

[RP3_APT_ASMA_2023]:      ../download/2023/RP3_APT_ASMA_2023_Jan_Dec.xlsx
[RP3_APT_ATC_PRE_2023]:   ../download/2023/RP3_APT_ATC_PRE_2023_Jan_Dec.xlsx
[RP3_APT_TxOut_2023]:     ../download/2023/RP3_APT_TxOut_2023_Jan_Dec.xlsx
[RP3_APT_ATFM_ARR_2023]:  ../download/2023/RP3_APT_ATFM_ARR_2023_Jan_Dec.xlsx
[RP3_APT_ATFM_SLOT_2023]: ../download/2023/RP3_APT_ATFM_SLOT_2023_Jan_Dec.xlsx
[RP3_ERT_ATFM_2023]:      ../download/2023/RP3_ERT_ATFM_2023_Jan_Dec.xlsx
[RP3_ERT_SU_2023]:        ../download/2023/RP3_ERT_SU_2023_Jan_Dec.xlsx
[RP3_Flights_2023]:       ../download/2023/RP3_Flights_2023_Jan_Dec.xlsx
[RP3_FLT_EFF_2023]:       ../download/2023/RP3_FLT_EFF_2023_Jan_Dec.xlsx
[RP3_CCO_CDO_2023]:       ../download/2023/RP3_APT_CDO_2023_Jan_Dec.xlsx


## 2022

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP3_APT_ASMA_2022_Jan_Dec.xlsx][RP3_APT_ASMA_2022]             |
| Share of arrivals applying CDO        | [{{% dwnld_i %}} RP3_APT_CDO_2022_Jan_Dec.xlsx][RP3_CCO_CDO_2022]             |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP3_APT_ATC_PRE_2022_Jan_Dec.xlsx][RP3_APT_ATC_PRE_2022]         |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP3_APT_ATFM_ARR_2022_Jan_Dec.xlsx][RP3_APT_ATFM_ARR_2022]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP3_APT_ATFM_SLOT_2022_Jan_Dec.xlsx][RP3_APT_ATFM_SLOT_2022] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP3_APT_TxOut_2022_Jan_Dec.xlsx][RP3_APT_TxOut_2022]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP3_ERT_ATFM_2022_Jan_Dec.xlsx][RP3_ERT_ATFM_2022]           |
| En-route Service Units                | [{{% dwnld_i %}} RP3_ERT_SU_2022_Jan_Dec.xlsx][RP3_ERT_SU_2022]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP3_Flights_2022_Jan_Dec.xlsx][RP3_Flights_2022]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP3_FLT_EFF_2022_Jan_Dec.xlsx][RP3_FLT_EFF_2022]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2022.xlsx][RP3_ERT_CEF_2022]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2022.xlsx][RP3_TRM_CEF_2022]             |

[RP3_APT_ASMA_2022]:      ../download/2022/RP3_APT_ASMA_2022_Jan_Dec.xlsx
[RP3_APT_ATC_PRE_2022]:   ../download/2022/RP3_APT_ATC_PRE_2022_Jan_Dec.xlsx
[RP3_APT_TxOut_2022]:     ../download/2022/RP3_APT_TxOut_2022_Jan_Dec.xlsx
[RP3_APT_ATFM_ARR_2022]:  ../download/2022/RP3_APT_ATFM_ARR_2022_Jan_Dec.xlsx
[RP3_APT_ATFM_SLOT_2022]: ../download/2022/RP3_APT_ATFM_SLOT_2022_Jan_Dec.xlsx
[RP3_ERT_ATFM_2022]:      ../download/2022/RP3_ERT_ATFM_2022_Jan_Dec.xlsx
[RP3_ERT_SU_2022]:        ../download/2022/RP3_ERT_SU_2022_Jan_Dec.xlsx
[RP3_Flights_2022]:       ../download/2022/RP3_Flights_2022_Jan_Dec.xlsx
[RP3_FLT_EFF_2022]:       ../download/2022/RP3_FLT_EFF_2022_Jan_Dec.xlsx
[RP3_CCO_CDO_2022]:       ../download/2022/RP3_APT_CDO_2022_Jan_Dec.xlsx
[RP3_ERT_CEF_2022]:       ../download/2022/RP3_ERT_CEF_2022.xlsx
[RP3_TRM_CEF_2022]:       ../download/2022/RP3_TRM_CEF_2022.xlsx

## 2021

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP3_APT_ASMA_2021_Jan_Dec.xlsx][RP3_APT_ASMA_2021]           |
| Share of arrivals applying CDO        | [{{% dwnld_i %}} RP3_APT_CDO_2021_Jan_Dec.xlsx][RP3_CCO_CDO_2021]             |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP3_APT_ATC_PRE_2021_Jan_Dec.xlsx][RP3_APT_ATC_PRE_2021]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP3_APT_ATFM_ARR_2021_Jan_Dec.xlsx][RP3_APT_ATFM_ARR_2021]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP3_APT_ATFM_SLOT_2021_Jan_Dec.xlsx][RP3_APT_ATFM_SLOT_2021] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP3_APT_TxOut_2021_Jan_Dec.xlsx][RP3_APT_TxOut_2021]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP3_ERT_ATFM_2021_Jan_Dec.xlsx][RP3_ERT_ATFM_2021]           |
| En-route Service Units                | [{{% dwnld_i %}} RP3_ERT_SU_2021_Jan_Dec.xlsx][RP3_ERT_SU_2021]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP3_Flights_2021_Jan_Dec.xlsx][RP3_Flights_2021]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP3_FLT_EFF_2021_Jan_Dec.xlsx][RP3_FLT_EFF_2021]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP3_ERT_CEF_2020_21.xlsx][RP3_ERT_CEF_2020_21]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP3_TRM_CEF_2020_21.xlsx][RP3_TRM_CEF_2020_21]             |

[RP3_APT_ASMA_2021]:      ../download/2021/RP3_APT_ASMA_2021_Jan_Dec.xlsx
[RP3_APT_ATC_PRE_2021]:   ../download/2021/RP3_APT_ATC_PRE_2021_Jan_Dec.xlsx
[RP3_APT_TxOut_2021]:     ../download/2021/RP3_APT_TxOut_2021_Jan_Dec.xlsx
[RP3_APT_ATFM_ARR_2021]:  ../download/2021/RP3_APT_ATFM_ARR_2021_Jan_Dec.xlsx
[RP3_APT_ATFM_SLOT_2021]: ../download/2021/RP3_APT_ATFM_SLOT_2021_Jan_Dec.xlsx
[RP3_ERT_ATFM_2021]:      ../download/2021/RP3_ERT_ATFM_2021_Jan_Dec.xlsx
[RP3_ERT_SU_2021]:        ../download/2021/RP3_ERT_SU_2021_Jan_Dec.xlsx
[RP3_Flights_2021]:       ../download/2021/RP3_Flights_2021_Jan_Dec.xlsx
[RP3_FLT_EFF_2021]:       ../download/2021/RP3_FLT_EFF_2021_Jan_Dec.xlsx
[RP3_CCO_CDO_2021]:       ../download/2021/RP3_APT_CDO_2021_Jan_Dec.xlsx
[RP3_ERT_CEF_2020_21]:       ../download/2021/RP3_ERT_CEF_2020_21.xlsx
[RP3_TRM_CEF_2020_21]:       ../download/2021/RP3_TRM_CEF_2020_21.xlsx

## 2020 (post operational adjustments are taken into account (Status 07 April 2021))

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP3_APT_ASMA_2020_Jan_Dec.xlsx][RP3_APT_ASMA_2020]           |
| Share of arrivals applying CDO        | [{{% dwnld_i %}} RP3_APT_CDO_2020_Jan_Dec.xlsx][RP3_CCO_CDO_2020]             |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP3_APT_ATC_PRE_2020_Jan_Dec.xlsx][RP3_APT_ATC_PRE_2020]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP3_APT_ATFM_ARR_2020_Jan_Dec.xlsx][RP3_APT_ATFM_ARR_2020]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP3_APT_ATFM_SLOT_2020_Jan_Dec.xlsx][RP3_APT_ATFM_SLOT_2020] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP3_APT_TxOut_2020_Jan_Dec.xlsx][RP3_APT_TxOut_2020]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP3_ERT_ATFM_2020_Jan_Dec.xlsx][RP3_ERT_ATFM_2020]           |
| En-route Service Units                | [{{% dwnld_i %}} RP3_ERT_SU_2020_Jan_Dec.xlsx][RP3_ERT_SU_2020]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP3_Flights_2020_Jan_Dec.xlsx][RP3_Flights_2020]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP3_FLT_EFF_2020_Jan_Dec.xlsx][RP3_FLT_EFF_2020]             |

[RP3_APT_ASMA_2020]:      ../download/2020/RP3_APT_ASMA_2020_Jan_Dec.xlsx
[RP3_APT_ATC_PRE_2020]:   ../download/2020/RP3_APT_ATC_PRE_2020_Jan_Dec.xlsx
[RP3_APT_TxOut_2020]:     ../download/2020/RP3_APT_TxOut_2020_Jan_Dec.xlsx
[RP3_APT_ATFM_ARR_2020]:  ../download/2020/RP3_APT_ATFM_ARR_2020_Jan_Dec.xlsx
[RP3_APT_ATFM_SLOT_2020]: ../download/2020/RP3_APT_ATFM_SLOT_2020_Jan_Dec.xlsx
[RP3_ERT_ATFM_2020]:      ../download/2020/RP3_ERT_ATFM_2020_Jan_Dec.xlsx
[RP3_ERT_SU_2020]:        ../download/2020/RP3_ERT_SU_2020_Jan_Dec.xlsx
[RP3_Flights_2020]:       ../download/2020/RP3_Flights_2020_Jan_Dec.xlsx
[RP3_FLT_EFF_2020]:       ../download/2020/RP3_FLT_EFF_2020_Jan_Dec.xlsx
[RP3_CCO_CDO_2020]:       ../download/2020/RP3_APT_CDO_2020_Jan_Dec.xlsx



## 2019 (post operational adjustments are taken into account (Status 16 April 2020))

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP2_APT_ASMA_2019_Jan_Dec.xlsx][RP2_APT_ASMA_2019]           |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP2_APT_ATC_PRE_2019_Jan_Dec.xlsx][RP2_APT_ATC_PRE_2019]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP2_APT_ATFM_ARR_2019_Jan_Dec.xlsx][RP2_APT_ATFM_ARR_2019]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP2_APT_ATFM_SLOT_2019_Jan_Dec.xlsx][RP2_APT_ATFM_SLOT_2019] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP2_APT_TxOut_2019_Jan_Dec.xlsx][RP2_APT_TxOut_2019]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP2_ERT_ATFM_2019_Jan_Dec.xlsx][RP2_ERT_ATFM_2019]           |
| En-route Service Units                | [{{% dwnld_i %}} RP2_ERT_SU_2019_Jan_Dec.xlsx][RP2_ERT_SU_2019]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP2_Flights_2019_Jan_Dec.xlsx][RP2_Flights_2019]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP2_FLT_EFF_2019_Jan_Dec.xlsx][RP2_FLT_EFF_2019]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2019.xlsx][RP2_ERT_CEF_2019]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2019.xlsx][RP2_TRM_CEF_2019]             |
| Effectiveness of Safety Management    | [{{% dwnld_i %}} RP2_SAF_EoSM_2019.xlsx][RP2_SAF_EoSM_2019]           |
| RAT Methodology Application           | [{{% dwnld_i %}} RP2_SAF_RAT_2019.xlsx][RP2_SAF_RAT_2019]             |
| Reporting of Just Culture             | [{{% dwnld_i %}} RP2_SAF_JC_2019.xlsx][RP2_SAF_JC_2019]               |


[RP2_APT_ASMA_2019]:      ../download/2019/RP2_APT_ASMA_2019_Jan_Dec.xlsx
[RP2_APT_ATC_PRE_2019]:   ../download/2019/RP2_APT_ATC_PRE_2019_Jan_Dec.xlsx
[RP2_APT_TxOut_2019]:     ../download/2019/RP2_APT_TxOut_2019_Jan_Dec.xlsx
[RP2_APT_ATFM_ARR_2019]:  ../download/2019/RP2_APT_ATFM_ARR_2019_Jan_Dec.xlsx
[RP2_APT_ATFM_SLOT_2019]: ../download/2019/RP2_APT_ATFM_SLOT_2019_Jan_Dec.xlsx
[RP2_ERT_ATFM_2019]:      ../download/2019/RP2_ERT_ATFM_2019_Jan_Dec.xlsx
[RP2_ERT_SU_2019]:        ../download/2019/RP2_ERT_SU_2019_Jan_Dec.xlsx
[RP2_Flights_2019]:       ../download/2019/RP2_Flights_2019_Jan_Dec.xlsx
[RP2_FLT_EFF_2019]:       ../download/2019/RP2_FLT_EFF_2019_Jan_Dec.xlsx
[RP2_ERT_CEF_2019]:       ../download/2019/RP2_ERT_CEF_2019.xlsx
[RP2_TRM_CEF_2019]:       ../download/2019/RP2_TRM_CEF_2019.xlsx
[RP2_SAF_EoSM_2019]:      ../download/2019/RP2_SAF_EoSM_2019.xlsx
[RP2_SAF_RAT_2019]:       ../download/2019/RP2_SAF_RAT_2019.xlsx
[RP2_SAF_JC_2019]:        ../download/2019/RP2_SAF_JC_2019.xlsx


## 2018 (post operational adjustments are taken into account (Status 29 April 2019))

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP2_APT_ASMA_2018_Jan_Dec.xlsx][RP2_APT_ASMA_2018]           |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP2_APT_ATC_PRE_2018_Jan_Dec.xlsx][RP2_APT_ATC_PRE_2018]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP2_APT_ATFM_ARR_2018_Jan_Dec.xlsx][RP2_APT_ATFM_ARR_2018]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP2_APT_ATFM_SLOT_2018_Jan_Dec.xlsx][RP2_APT_ATFM_SLOT_2018] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP2_APT_TxOut_2018_Jan_Dec.xlsx][RP2_APT_TxOut_2018]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP2_ERT_ATFM_2018_Jan_Dec.xlsx][RP2_ERT_ATFM_2018]           |
| En-route Service Units                | [{{% dwnld_i %}} RP2_ERT_SU_2018_Jan_Dec.xlsx][RP2_ERT_SU_2018]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP2_Flights_2018_Jan_Dec.xlsx][RP2_Flights_2018]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP2_FLT_EFF_2018_Jan_Dec.xlsx][RP2_FLT_EFF_2018]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2018.xlsx][RP2_ERT_CEF_2018]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2018.xlsx][RP2_TRM_CEF_2018]             |
| Effectiveness of Safety Management    | [{{% dwnld_i %}} RP2_SAF_EoSM_2018.xlsx][RP2_SAF_EoSM_2018]           |
| RAT Methodology Application           | [{{% dwnld_i %}} RP2_SAF_RAT_2018.xlsx][RP2_SAF_RAT_2018]             |
| Reporting of Just Culture             | [{{% dwnld_i %}} RP2_SAF_JC_2018.xlsx][RP2_SAF_JC_2018]               |

[RP2_APT_ASMA_2018]:      ../download/2018/RP2_APT_ASMA_2018_Jan_Dec.xlsx
[RP2_APT_ATC_PRE_2018]:   ../download/2018/RP2_APT_ATC_PRE_2018_Jan_Dec.xlsx
[RP2_APT_ATFM_ARR_2018]:  ../download/2018/RP2_APT_ATFM_ARR_2018_Jan_Dec.xlsx
[RP2_APT_ATFM_SLOT_2018]: ../download/2018/RP2_APT_ATFM_SLOT_2018_Jan_Dec.xlsx
[RP2_APT_TxOut_2018]:     ../download/2018/RP2_APT_TxOut_2018_Jan_Dec.xlsx
[RP2_ERT_ATFM_2018]:      ../download/2018/RP2_ERT_ATFM_2018_Jan_Dec.xlsx
[RP2_ERT_SU_2018]:        ../download/2018/RP2_ERT_SU_2018_Jan_Dec.xlsx
[RP2_Flights_2018]:       ../download/2018/RP2_Flights_2018_Jan_Dec.xlsx
[RP2_FLT_EFF_2018]:       ../download/2018/RP2_FLT_EFF_2018_Jan_Dec.xlsx
[RP2_ERT_CEF_2018]:       ../download/2018/RP2_ERT_CEF_2018.xlsx
[RP2_TRM_CEF_2018]:       ../download/2018/RP2_TRM_CEF_2018.xlsx
[RP2_SAF_EoSM_2018]:      ../download/2018/RP2_SAF_EoSM_2018.xlsx
[RP2_SAF_RAT_2018]:       ../download/2018/RP2_SAF_RAT_2018.xlsx
[RP2_SAF_JC_2018]:        ../download/2018/RP2_SAF_JC_2018.xlsx

## 2017

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP2_APT_ASMA_2017.xlsx][RP2_APT_ASMA_2017]           |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP2_APT_ATC_PRE_2017.xlsx][RP2_APT_ATC_PRE_2017]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP2_APT_ATFM_ARR_2017.xlsx][RP2_APT_ATFM_ARR_2017]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP2_APT_ATFM_SLOT_2017.xlsx][RP2_APT_ATFM_SLOT_2017] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP2_APT_TxOut_2017.xlsx][RP2_APT_TxOut_2017]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP2_ERT_ATFM_2017.xlsx][RP2_ERT_ATFM_2017]           |
| En-route Service Units                | [{{% dwnld_i %}} RP2_ERT_SU_2017.xlsx][RP2_ERT_SU_2017]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP2_Flights_2017.xlsx][RP2_Flights_2017]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP2_FLT_EFF_2017.xlsx][RP2_FLT_EFF_2017]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2017.xlsx][RP2_TRM_CEF_2017]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2017.xlsx][RP2_ERT_CEF_2017]             |
| Effectiveness of Safety Management    | [{{% dwnld_i %}} RP2_SAF_EoSM_2017.xlsx][RP2_SAF_EoSM_2017]           |
| RAT Methodology Application           | [{{% dwnld_i %}} RP2_SAF_RAT_2017.xlsx][RP2_SAF_RAT_2017]             |
| Reporting of Just Culture             | [{{% dwnld_i %}} RP2_SAF_JC_2017.xlsx][RP2_SAF_JC_2017]               |


[RP2_APT_ASMA_2017]:      ../download/2017/RP2_APT_ASMA_2017.xlsx
[RP2_APT_ATC_PRE_2017]:   ../download/2017/RP2_APT_ATC_PRE_2017.xlsx
[RP2_APT_ATFM_ARR_2017]:  ../download/2017/RP2_APT_ATFM_ARR_2017.xlsx
[RP2_APT_ATFM_SLOT_2017]: ../download/2017/RP2_APT_ATFM_SLOT_2017.xlsx
[RP2_APT_TxOut_2017]:     ../download/2017/RP2_APT_TxOut_2017.xlsx
[RP2_ERT_ATFM_2017]:      ../download/2017/RP2_ERT_ATFM_2017.xlsx
[RP2_ERT_SU_2017]:        ../download/2017/RP2_ERT_SU_2017.xlsx
[RP2_Flights_2017]:       ../download/2017/RP2_Flights_2017.xlsx
[RP2_FLT_EFF_2017]:       ../download/2017/RP2_FLT_EFF_2017.xlsx
[RP2_TRM_CEF_2017]:       ../download/2017/RP2_TRM_CEF_2017.xlsx
[RP2_ERT_CEF_2017]:       ../download/2017/RP2_ERT_CEF_2017.xlsx
[RP2_SAF_EoSM_2017]:      ../download/2017/RP2_SAF_EoSM_2017.xlsx
[RP2_SAF_RAT_2017]:       ../download/2017/RP2_SAF_RAT_2017.xlsx
[RP2_SAF_JC_2017]:        ../download/2017/RP2_SAF_JC_2017.xlsx



## 2016

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP2_APT_ASMA_2016.xlsx][RP2_APT_ASMA_2016]           |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP2_APT_ATC_PRE_2016.xlsx][RP2_APT_ATC_PRE_2016]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP2_APT_ATFM_ARR_2016.xlsx][RP2_APT_ATFM_ARR_2016]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP2_APT_ATFM_SLOT_2016.xlsx][RP2_APT_ATFM_SLOT_2016] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP2_APT_TxOut_2016.xlsx][RP2_APT_TxOut_2016]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP2_ERT_ATFM_2016.xlsx][RP2_ERT_ATFM_2016]           |
| En-route Service Units                | [{{% dwnld_i %}} RP2_ERT_SU_2016.xlsx][RP2_ERT_SU_2016]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP2_Flights_2016.xlsx][RP2_Flights_2016]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP2_FLT_EFF_2016.xlsx][RP2_FLT_EFF_2016]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2016.xlsx][RP2_TRM_CEF_2016]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2016.xlsx][RP2_ERT_CEF_2016]             |


[RP2_APT_ASMA_2016]:     ../download/2016/RP2_APT_ASMA_2016.xlsx
[RP2_APT_ATC_PRE_2016]:   ../download/2016/RP2_APT_ATC_PRE_2016.xlsx
[RP2_APT_ATFM_ARR_2016]:  ../download/2016/RP2_APT_ATFM_ARR_2016.xlsx
[RP2_APT_ATFM_SLOT_2016]: ../download/2016/RP2_APT_ATFM_SLOT_2016.xlsx
[RP2_APT_TxOut_2016]:     ../download/2016/RP2_APT_TxOut_2016.xlsx
[RP2_ERT_ATFM_2016]:      ../download/2016/RP2_ERT_ATFM_2016.xlsx
[RP2_ERT_SU_2016]:        ../download/2016/RP2_ERT_SU_2016.xlsx
[RP2_Flights_2016]:       ../download/2016/RP2_Flights_2016.xlsx
[RP2_FLT_EFF_2016]:       ../download/2016/RP2_FLT_EFF_2016.xlsx
[RP2_TRM_CEF_2016]:       ../download/2016/RP2_TRM_CEF_2016.xlsx
[RP2_ERT_CEF_2016]:       ../download/2016/RP2_ERT_CEF_2016.xlsx



## 2015

| Description                           |  Files/Link                                                           |
|---------------------------------------|-----------------------------------------------------------------------|
| Additional Time in Terminal Airspace  | [{{% dwnld_i %}} RP2_APT_ASMA_2015.xlsx][RP2_APT_ASMA_2015]           |
| Airport Pre-departure Delay           | [{{% dwnld_i %}} RP2_APT_ATC_PRE_2015.xlsx][RP2_APT_ATC_PRE_2015]     |
| Airport ATFM Arrival Delay            | [{{% dwnld_i %}} RP2_APT_ATFM_ARR_2015.xlsx][RP2_APT_ATFM_ARR_2015]   |
| Adherence to ATFM slots               | [{{% dwnld_i %}} RP2_APT_ATFM_SLOT_2015.xlsx][RP2_APT_ATFM_SLOT_2015] |
| Airport Additional Taxi-out Time      | [{{% dwnld_i %}} RP2_APT_TxOut_2015.xlsx][RP2_APT_TxOut_2015]         |
| En-route ATFM delay per Flight        | [{{% dwnld_i %}} RP2_ERT_ATFM_2015.xlsx][RP2_ERT_ATFM_2015]           |
| En-route Service Units                | [{{% dwnld_i %}} RP2_ERT_SU_2015.xlsx][RP2_ERT_SU_2015]               |
| Average daily IFR Flight              | [{{% dwnld_i %}} RP2_Flights_2015.xlsx][RP2_Flights_2015]             |
| Horizontal En-route Flight Efficiency | [{{% dwnld_i %}} RP2_FLT_EFF_2015.xlsx][RP2_FLT_EFF_2015]             |
| Terminal Cost efficiency              | [{{% dwnld_i %}} RP2_TRM_CEF_2015.xlsx][RP2_TRM_CEF_2015]             |
| En route Cost efficiency              | [{{% dwnld_i %}} RP2_ERT_CEF_2015.xlsx][RP2_ERT_CEF_2015]             |


[RP2_APT_ASMA_2015]:      ../download/2015/RP2_APT_ASMA_2015.xlsx
[RP2_APT_ATC_PRE_2015]:   ../download/2015/RP2_APT_ATC_PRE_2015.xlsx
[RP2_APT_ATFM_ARR_2015]:  ../download/2015/RP2_APT_ATFM_ARR_2015.xlsx
[RP2_APT_ATFM_SLOT_2015]: ../download/2015/RP2_APT_ATFM_SLOT_2015.xlsx
[RP2_APT_TxOut_2015]:     ../download/2015/RP2_APT_TxOut_2015.xlsx
[RP2_ERT_ATFM_2015]:      ../download/2015/RP2_ERT_ATFM_2015.xlsx
[RP2_ERT_SU_2015]:        ../download/2015/RP2_ERT_SU_2015.xlsx
[RP2_Flights_2015]:       ../download/2015/RP2_Flights_2015.xlsx
[RP2_FLT_EFF_2015]:       ../download/2015/RP2_FLT_EFF_2015.xlsx
[RP2_TRM_CEF_2015]:       ../download/2015/RP2_TRM_CEF_2015.xlsx
[RP2_ERT_CEF_2015]:       ../download/2015/RP2_ERT_CEF_2015.xlsx
