---
title: "Reporting Period 2 - 2016 dashboard"
date: 2016-01-01
categories: ["dashboard"]
aliases:
  - /rp2_2016.html
extrajs: [
  "/javascript/load_google.js",
  "/javascript/draw_vis.js",
  "/javascript/2016/crt_ertfltsYY_16.js",
  "/javascript/2016/crt_ertfltsMM_16.js",
  "/javascript/2016/tbl_ertfltsYY_16.js",
  "/javascript/2016/crt_flteffYY_16.js",
  "/javascript/2016/crt_flteffMM_16.js",
  "/javascript/2016/tbl_ert_flteff_16.js",
  "/javascript/2016/tbl_txdly_LOC_16.js",
  "/javascript/2016/tbl_txdly_APT_16.js",
  "/javascript/2016/tbl_ASMAdly_LOC_16.js",
  "/javascript/2016/tbl_ASMAdly_APT_16.js",
  "/javascript/2016/crt_ertdlyYY_16.js",
  "/javascript/2016/crt_ertdlyMM_16.js",
  "/javascript/2016/tbl_ertdly_YYtgt_16.js",
  "/javascript/2016/crt_aptATFMsesYY_16.js",
  "/javascript/2016/crt_aptATFMsesMM_16.js",
  "/javascript/2016/tbl_aptATFM_LOC_16.js",
  "/javascript/2016/tbl_aptATFM_APT_16.js",
  "/javascript/2016/tbl_aptATFMADH_LOC_16.js",
  "/javascript/2016/tbl_aptATFMADH_APT_16.js",
  "/javascript/2016/tbl_aptATC_LOC_16.js",
  "/javascript/2016/tbl_aptATC_APT_16.js",
  "/javascript/2016/tbl_ertSU_16.js",
  "/javascript/2016/crt_ertSUYYvstgt_16.js",
  "/javascript/2016/crt_EoSMYY_AN_16.js",
  "/javascript/2016/crt_EoSMYY_ST_16.js",
  "/javascript/2016/tbl_EOSM_ANSP_16.js",
  "/javascript/2016/tbl_EOSM_FAB1_16.js",
  "/javascript/2016/tbl_EOSM_STA_16.js",
  "/javascript/2016/crt_RAT_16.js",
  "/javascript/2016/tbl_trcef_fab_16.js",
  "/javascript/2016/tbl_trcef_state_16.js",
  "/javascript/2016/tbl_ertcef_fab_16.js",
  "/javascript/2016/tbl_ertcef_state_16.js",
  ]
---

<script type="text/javascript" src="//www.google.com/jsapi"></script>

The data and indicators for [reference period 2][ref2] are in accordance with Implementing Regulations (EU) [No 390/2013][no390_2013] and (EU) [No 391/2013][no391_2013].

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="2" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;Traffic</div>
</td>
</tr>

<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Average daily IFR flights</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1Ip-cVibeSuNUR3Hgt_EmfN2hUh-cJyh-gXSy_wKV-20/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/minutes-of-en-route-atfm-delay-per-flight.Rmd" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_ertfltsYY_16"></div>
<div style="float: left;" id="crt_ertfltsMM_16"></div>

<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ertflts_YY_16"></div>

</tr>
</tbody>
</table>
</tbody>
</table>


<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;SAFETY</div>
</td>
</tr>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Safety KPI #1: Effectiveness of safety management (EoSM)</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1leb0YXcEDIvbQiMJ3bKZcLNxDNrLTSMm3jsmmwr2Lrs/edit?usp=sharing" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: EASA</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/effectiveness-of-safety-management.md" >}}' target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="crt_EoSMYY_ST_16"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="crt_EoSMYY_AN_16"></div>
</td>
</tr>
<tr>
<td colspan="4" rowspan="1" style="width: 950px; vertical-align: top;">
<div><b>FAB level</b></div>
<div style="float: top;" id="tbl_EOSM_FAB1_16"></div>
</tr>
<br>
<tr>
<td colspan="4" rowspan="1" style="width: 950px; vertical-align: top;">
<br>
<div><b>State level</b></div>
<div style="float: top;" id="tbl_EOSM_STA_16"></div>
</td>
</tr>
<tr>
<td colspan="4" rowspan="1" style="width: 950px; vertical-align: top;">
<br>
<div><b>ANSP level</b></div>
<div style="float: top;" id="tbl_EOSM_ANSP_16"></div>
</td>
<br>
</tr>
</tbody>
</table>
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<br>
<tr>
<td colspan="3" rowspan="1" style="width: 475px, text-align: center; vertical-align: top;">
<div class="head4">&nbsp;RAT methodology application&nbsp;&nbsp;
<a href='{{< relref "/metadata/rat-methodology-application.md" >}}' target="_blank">(Meta data)</a></div>
</td>
<td colspan="3" rowspan="1" style="width: 475px, text-align: center; vertical-align: top;">
<div class="head4">&nbsp;Reporting of Just Culture &nbsp;&nbsp;
<a href='{{< relref "/metadata/reporting-of-just-culture.md" >}}' target="_blank">(Meta data)</a> </div>
</td>
</tr>
<tr>
<td>
<div style="width: 175px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 150px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/160-P769ewud3-dcR7kwhw6m7g0acg8ldp_9zdYCfm9c/edit?usp=sharing" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 125px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: DPS/SSR</div>
</td>
<td>
<div style="width: 175px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 150px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1Ck1CEYiWZnN_C716rH7UHvCe7WXvB52Uhpnc_qLpA64/edit?usp=sharing" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 125px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: EASA</div>
</td>
</tr>
<tr>
<td colspan="3" rowspan="1">
<div style="float: top;" id="crt_RAT_16"></div>
</td>
<td colspan="3" rowspan="1">
<div style="text-align: left; vertical-align: top">
<p>There are no just culture results at European wide level.
<br>The 2016 results at State and ANSP level can be found in the download file</p>
<p><small><i>&nbsp;Note that the total number of "NO" answers may not reflect an absence of Just Culture.</i></small></p>
</div>
</td>
</tr>
</tbody>
</table>
</tbody>
</table>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp; ENVIRONMENT</div>
</td>
</tr>

<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp;Environment KPI #1: Horizontal en-route flight efficiency [%]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1N0EH3rG0k-9ornfJXWWPks8iKBB8LBsx9WyqljHhc8c/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/average-horizontal-en-route-inefficiency.md" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_flteffYY_16"></div>
<div style="float: left;" id="crt_flteffMM_16"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ert_flteff_16"></div>
</tr>
</tbody>
</table><br>

<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Environment PI #1: Additional taxi-out time [minutes per departure]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1hLYGdDDyS6-6IXVyblXZiWptQ2FB818qoCn2g0msKas/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: PRU analysis; Airports</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/additional-taxi-out-time.html" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_txdly_LOC_16"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_txdly_APT_16"></div></td>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Environment PI #2: Additional time in terminal airspace [minutes per arrival]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1MdhOPUqTN4nvVcyU0LsfBJ3uNOGjv7x5O1VzQKekILg/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>

<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Airports; Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/additional-asma-time.html" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ASMAdly_LOC_16"></div><br>	</td>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top" id="tbl_ASMAdly_APT_16"></div><br>	</td>
</tr>
</tbody>
</table>

</tbody>
</table>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;CAPACITY</div>
<span style="color:#C0504D;">Please note that software release 20.0 of the Network Manager on 04 April 2016 introduced a change in the computation of ATFM delay for operational purposes. For consistency reasons, ATFM delays on this web page will continue to be based on the methodology used before April 2016. As a result, the data published on this website might deviate from the data directly published by EUROCONTROL for operational purposes.
See the Meta data for more information on the changes in NM release 20.0.<br><br>
Changes due to the <a href="https://www.eurocontrol.int/publications/post-operations-performance-adjustment-process" target="_blank">[Post Operations Adjustment Process]</a> will only be taken into account when the full year 2016 is available.
</span>
</td>
</tr>

<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity KPI #1: En-route ATFM delay per flight [minutes per flight]</div>
</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1qrQvx2VBM5ig-HGvIIbHk_kkjJoQa5Wx0QOtC_4xIPE/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>

</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/minutes-of-en-route-atfm-delay-per-flight.Rmd" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_ertdlyYY_16"></div>
<div style="float: left;" id="crt_ertdlyMM_16"></div>

<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ertdly_YYtgt_16"></div>

</tr>
</tbody>
</table><br>


<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity KPI #2: Airport ATFM arrival delay per flight [min./arr.]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1_4ov3Bh400d9X2MNkXt8nH3BBpD7ipyhZULbKuGEAI4/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/airport-atfm-delay.md" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_aptATFMsesYY_16"></div><br><br>
<div style="float: top;" id="tbl_aptATFM_LOC_16"></div>


<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_aptATFMsesMM_16"></div><br><br>
<div style="float: top;" id="tbl_aptATFM_APT_16"></div>

</tr>
</tbody>
</table>	<br>

<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity PI #1: Adherence to ATFM slots [% flights inside the slot tolerance window of [-5, +10 min.]]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1aXO6pvE4Q6m7auDAGJv2VwXUOUd00-zfdLJbMBRYbkY/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/atfm-slot-adherence.md" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATFMADH_LOC_16"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATFMADH_APT_16"></div>
</tr>
</tbody>
</table><br>


<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity PI #2: Air traffic control pre-departure delay [min. per dep.]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="//docs.google.com/spreadsheets/d/1fbGRbNRWg6XJyhGIuA-LgacvNGUtdLU_CqbtvP9Wwjo/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div></td>

<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: Airports</div></td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/atc-pre-departure-delay.md" >}}' target="_blank">[Meta data]</a>
</span></div></td>

</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATC_LOC_16"></div></td>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATC_APT_16"></div></td>
</tr>
</tbody>
</table><br>

</tbody>
</table>


<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>

<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;COST-EFFICIENCY</div>
</td>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; En-route Service Units (TSU)[actual vs. determined]</div>
</td>
</tr>

<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1vr98Lgny8K4enpo3NhXVUIS0tqJ0Xf1SonxfeZwnv9g/edit?usp=sharing" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: CRCO; EC; PRU analysis </div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
</span></div>
</td>
</tr>

<tr>
<td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
<div class="head4">&nbsp;En-route TSU: by charging zones (2016)</div>
<div style="text-align: left; vertical-align: top;"></div>
<div style="float: top;" id="tbl_ertSU_16"></div>
<br>
</td>
<td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
<div class="head4">&nbsp;En-route TSU: actual vs. determined (2016)</div>
<div style="text-align: left; vertical-align: top;"></div>
<div style="float: top;" id="crt_ertSUYYvstgt_16"></div>
</td>
</tr>
</tbody>
</table>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Cost efficiency KPI #1: Determined unit cost (DUC) for en-route (ER) ANS</div>
</td>
</tr>

<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1Q6DzCPVQP07T2yYBM9O9QjV6QmjGi7ehlMzezI4hsPY/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: States, CRCO</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/rp2.md" >}}' target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<br>

<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<span style="color:#C0504D;">The figures shown below are expressed in real term (Euro 2009). The underlying data (currencies, etc.) are available in the download file.
(D)=Determined ; (A)=Actual
</span>
</td>
</tr>
</tbody>
</table>

<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_ertcef_state_16"></div>
</td>
<br>
</tr>

<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_ertcef_fab_16"></div>
</td>
</tr>
</tbody>
</table>

<br>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Cost efficiency KPI #2: Determined unit cost (DUC) for terminal (TR) ANS</div>
</td>
</tr>

<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/11HvNJxV1uOvywak5seqy2CXGEKWl7jUJVdBO_MrE98w/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: States, CRCO</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href='{{< relref "/metadata/rp2.md" >}}' target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>

<br>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<span style="color:#C0504D;">The figures shown below are expressed in real term (Euro 2009). The underlying data (currencies, etc.) are available in the download file.
(D)=Determined ; (A)=Actual
</span>
</td>
</tr>

</tbody>
</table>

<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_trcef_state_16"></div>
</td>
<br>
</tr>

<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_trcef_fab_16"></div>
</td>
</tr>

</tbody>
</table>





[no317_2019]: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2019.056.01.0001.01.ENG "IR 317/2019"
[no390_2013]: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32013R0390 "IR 390/2019"
[no391_2013]: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32013R0391 "IR 391/2019"
[ref2]: ../../metadata/rp2/ "Reference Period 2"