---
title: "Reporting Period 2 - 2018 dashboard"
date: 2018-01-01
categories: ["dashboard"]
aliases:
  - /rp2_2018.html
---

<script type="text/javascript" src="//www.google.com/jsapi"></script>
<script type="text/javascript">
// load the visualisation API
google.load('visualization', '1', {
    packages: ['corechart', 'controls']
});
</script>
<script type="text/javascript">
function drawVisualization() {


  // TRAFFIC - ERT FLTS - YY - CHART
    var crt_ertfltsYY = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_ertfltsYY',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/16WgqQjV0jXiGI2TOPk2XKsRvrAtMrL_8p7t2Nr2k2PM/edit?usp=sharing&sheet=ERT_FLTS_YY&range=A5:E10',
        options: {
            width: 450,
            height: 170,
            chartArea: {
                left: 80,
                top: 30,
                width: '60%',
                height: '65%'
            },
            title: 'Average daily IFR flights (EU-wide)',
            titleTextStyle: {
                color: '#1F1F2E',
                fontSize: 12
            },
            legend: 'none',
            series: {
                0: {
                    type: 'bars',
                    color: '#7DD2F2',
                    targetAxisIndex: 0
                },
                1: {
                    type: 'lines',
                    color: '#B89470',
                    lineWidth: 2,
                    pointSize: 7,
                    targetAxisIndex: 1
                }
            },
            vAxes: {
                0: {
                    title: 'Avg. daily IFR flights',
                    titleTextStyle: {
                        color: '#1F1F2E',
                        fontSize: 11
                    },
                    minValue: 0.00,
                    textStyle: {
                        color: '#1F1F2E'
                    }
                },
                1: {
                    title: 'year on year (%)',
                    titleTextStyle: {
                        color: '#1F1F2E',
                        fontSize: 11
                    },
                    maxValue: 0.04,
                    textStyle: {
                        color: '#B89470'
                    }
                }
            }
        },
        view: {
            columns: [0, 3, 4],
            rows: [0, 1, 2, 3, 4]
        }
    });
    crt_ertfltsYY.draw();


  // TRAFFIC - ERT FLTS - MM - CHART
    var crt_ertfltsMM = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_ertfltsMM',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/16WgqQjV0jXiGI2TOPk2XKsRvrAtMrL_8p7t2Nr2k2PM/edit?usp=sharing&sheet=ERT_FLTS_MM&range=A4:I64&tq=where%20I%3D1',
        options: {
            width: 450,
            height: 190,
            chartArea: {
                left: 80,
                top: 30,
                width: '60%',
                height: '60%'
            },
            title: 'Avg. daily IFR flights',
            titleTextStyle: {
                color: 'grey',
                fontSize: 12
            },
            legend: 'none',
            series: {
                0: {
                    type: 'bars',
                    color: '#7DD2F2',
                    targetAxisIndex: 0
                },
                1: {
                    type: 'lines',
                    color: '#B89470',
                    lineWidth: 2,
                    pointSize: 6,
                    targetAxisIndex: 1
                }
            },
            vAxes: {
                0: {
                    title: 'Avg. daily IFR flights',
                    titleTextStyle: {
                        color: '#1F1F2E',
                        fontSize: 11
                    },
                    minValue: 0.00,
                    textStyle: {
                        color: '#1F1F2E'
                    }
                },
                1: {
                    title: 'cum. change vs. prev. year (%)',
                    titleTextStyle: {
                        color: '#1F1F2E',
                        fontSize: 11
                    },
                    maxValue: 0.04,
                    textStyle: {
                        color: '#B89470'
                    }
                }
            }
        },
        view: {
            columns: [2, 6, 7]
        }
    });
    crt_ertfltsMM.draw();


  // TRAFFIC - ERT FLTS - TABLE
    var tbl_ertflts_YY = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ertflts_YY',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/16WgqQjV0jXiGI2TOPk2XKsRvrAtMrL_8p7t2Nr2k2PM/edit?usp=sharing&sheet=ERT_FLTS_LOC&range=A5:F15',
        options: {
            allowHtml: false,
            width: 470,
            height: 340
        },
        view: {
            columns: [0, 3, 4, 5]
        }
    });
    tbl_ertflts_YY.draw();


  // ENVIRONMENT - Horizontal flight efficiency - YY - CHART
    var crt_flteffYY = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_flteffYY',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1wiPo8B2UOyc3ULZJiBPVk1qGcRpId4WMfjoRaRotpVs/edit?usp=sharing&sheet=FLT_EFF_YY&range=A5:G10',
        options: {
            width: 450,
            height: 180,
            chartArea: {
                left: 50,
                top: 30,
                width: '55%',
                height: '60%'
            },
            title: 'Horiz. en-route flight efficiency (yearly)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            series: {
                1: {
                    type: 'lines',
                    color: '#5D7CBA',
                    lineWidth: 1,
                    pointSize: 3
                },
                0: {
                    type: 'lines',
                    color: '#5D7CBA',
                    lineWidth: 1,
                    lineDashStyle: [6, 3]
                },
                3: {
                    type: 'lines',
                    color: '#c0504d',
                    lineWidth: 1,
                    pointSize: 4,
                    pointShape: 'diamond',
                },
                2: {
                    type: 'lines',
                    color: '#C0504D',
                    lineWidth: 1,
                    lineDashStyle: [6, 3]
                }
            },
            vAxis: {
                title: 'Inefficiency (%)',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                },
                minValue: 0.02,
                maxValue: 0.06,
                viewWindow: {
                    min: 0.02,
                    max: 0.06
                },
                format: '0.0%'
            },
            hAxis: {
                title: 'Annual values for the SES-RP2 area',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            columns: [1, 3, 4, 5, 6],
            rows: [0, 1, 2, 3, 4]
        }
    });
    crt_flteffYY.draw();


  // ENVIRONMENT - Horizontal flight efficiency - MM - CHART
    var crt_flteffMM = new google.visualization.ChartWrapper({
        chartType: 'LineChart',
        containerId: 'crt_flteffMM',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1wiPo8B2UOyc3ULZJiBPVk1qGcRpId4WMfjoRaRotpVs/edit?usp=sharing&sheet=FLT_EFF_MM&range=A5:F65&tq=where%20F%3D1',
        options: {
            width: 450,
            height: 190,
            chartArea: {
                left: 50,
                top: 30,
                width: '55%',
                height: '50%'
            },
            title: 'Horiz. en-route flight efficiency (monthly)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            series: {
                0: {
                    type: 'lines',
                    color: '#c0504d',
                    lineWidth: 1,
                    pointSize: 4,
                    pointShape: 'diamond'
                },
                1: {
                    type: 'lines',
                    color: '#5D7CBA',
                    lineWidth: 1,
                    pointSize: 3
                }
            },
            vAxis: {
                title: 'Inefficiency (%)',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                },
                minValue: 0.02,
                maxValue: 0.06,
                viewWindow: {
                    min: 0.02,
                    max: 0.06
                },
                format: '0.0%'
            },
            hAxis: {
                title: 'Monthly values for the SES-RP2 area',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                },
                type: 'string',
                slantedText: true,
                slantedTextAngle: 40,
                textStyle: {
                    fontSize: 11
                }
            }
        },
        view: {
            'columns': [0, 3, 4]
        }
    });
    crt_flteffMM.draw();

  // ENVIRONMENT - Horizontal flight efficiency - TABLE
    var tbl_ert_flteff = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ert_flteff',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1wiPo8B2UOyc3ULZJiBPVk1qGcRpId4WMfjoRaRotpVs/edit?usp=sharing&sheet=ERT_FLT_EFF_FAB&range=A5:E15&hl=en_GB',
        options: {
            allowHtml: true,
            width: 470,
            height: 360,
            //style: {fontSize: 9}
        },
        view: {
            columns: [0, 2, 3, 4]
        }
    });
    tbl_ert_flteff.draw();

  // ENVIRONMENT - ASMA DLY - LOC - TABLE
    var tbl_ASMAdly_LOC = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ASMAdly_LOC',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1MsscCX4tqDwskuuBdwmUK0GxL1fq9sVOuYS65yYybkc/edit?usp=sharing&sheet=ASMA_LOC&range=A5:F35',
        options: {
            allowHtml: false,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 5, 1]
        }
    });
    tbl_ASMAdly_LOC.draw();
    // ENVIRONMENT - ASMA DLY - APT - TABLE
    var tbl_ASMAdly_APT = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ASMAdly_APT',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1MsscCX4tqDwskuuBdwmUK0GxL1fq9sVOuYS65yYybkc/edit?usp=sharing&sheet=ASMA_APT&range=A5:G180',
        options: {
            allowHtml: false,
            width: 470,
            height: 280
        },
        view: {
            columns: [1, 2, 0, 3]
        }
    });
    tbl_ASMAdly_APT.draw();

  // ENVIRONMENT - TAXI OUT DLY - LOC - TABLE
    var tbl_txdly_LOC = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_txdly_LOC',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1z7ZrWrFAW-y7NycuZ-_65FfV8J4xmAsgtHaNyyqIpSo/edit?usp=sharing&sheet=TxOut_LOC&range=A5:F35',
        options: {
            allowHtml: false,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 5, 1]
        }
    });
    tbl_txdly_LOC.draw();
    // ENVIRONMENT - TAXI OUT DLY - APT - TABLE
    var tbl_txdly_APT = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_txdly_APT',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1z7ZrWrFAW-y7NycuZ-_65FfV8J4xmAsgtHaNyyqIpSo/edit?usp=sharing&sheet=TxOut_APT&range=A5:G180',
        options: {
            allowHtml: false,
            width: 470,
            height: 280
        },
        view: {
            columns: [1, 2, 0, 3]
        }
    });
    tbl_txdly_APT.draw();

  // CAPACITY - En-route ATFM delay - YY - CHART
    var crt_ertdlyYY = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_ertdlyYY',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1H4jmSgWZbOviUsPRjLrJCRqzdWA2kQ4AKetTS87qZWc/edit?usp=sharing&alt=json&sheet=ERT_ATFM_YY&range=A5:F10',
        options: {
            width: 450,
            height: 160,
            chartArea: {
                left: 50,
                top: 30,
                width: '55%',
                height: '60%'
            },
            title: 'En-route ATFM delays (SES RP2 area)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            isStacked: 'true',
            series: {
                1: {
                    type: 'bars',
                    color: '#7DD2F2'
                },
                0: {
                    type: 'lines',
                    color: 'D80032',
                    lineWidth: 0.5,
                    pointSize: 7
                }
            },
            vAxis: {
                title: 'minutes per flight',
                format: '0.00',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            'columns': [0, 4, 1]
        }
    });
    crt_ertdlyYY.draw();

  // CAPACITY - En-route ATFM delay - MM - CHART
    var crt_ertdlyMM = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_ertdlyMM',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1H4jmSgWZbOviUsPRjLrJCRqzdWA2kQ4AKetTS87qZWc/edit?usp=sharing&sheet=ERT_ATFM_MM&range=A5:G65&tq=where%20G%3D1',
        options: {
            width: 450,
            height: 190,
            chartArea: {
                left: 80,
                top: 30,
                width: '60%',
                height: '60%'
            },
            title: 'En-route ATFM delays (SES RP2 Area)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            isStacked: 'true',
            series: {
                0: {
                    type: 'lines',
                    color: '#5D7CBA',
                    lineWidth: 1,
                    pointSize: 6
                },
                1: {
                    type: 'bars',
                    color: '#7DD2F2'
                }
            },
            vAxis: {
                title: 'minutes per flight',
                format: '0.00',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            'columns': [1, 5, 2]
        }
    });
    crt_ertdlyMM.draw();

  // ERT ATFM DLY - YY EU wide - TABLE
    var tbl_ertdly_YYtgt = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ertdly_YYtgt',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1H4jmSgWZbOviUsPRjLrJCRqzdWA2kQ4AKetTS87qZWc/edit?usp=sharing&sheet=ERT_ATFM_LOC&range=A5:F15&hl=en_GB',
        options: {
            allowHtml: false,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 1, 4, 5]
        }
    });
    tbl_ertdly_YYtgt.draw();


  // CAPACITY - Airport ATFM arrival delay - YY - CHART
    var crt_aptATFMsesYY = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_aptATFMsesYY',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1k_t67KvHBoUAa42kdHK2AtT1YiW_zOTOw_rXMjeFsBw/edit?usp=sharing&sheet=APT_ATFM_SES_YY&range=A5:D10',
        options: {
            width: 450,
            height: 190,
            chartArea: {
                left: 80,
                top: 30,
                width: '60%',
                height: '60%'
            },
            title: 'Airport ATFM arrival delays (SES-RP2 airports)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            isStacked: 'true',
            seriesType: 'bars',
            colors: ['#7DD2F2'],
            vAxis: {
                title: 'minutes per arrival',
                format: '0.00',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            columns: [0, 1],
            rows: [0, 1, 2, 3, 4]
        }
    });
    crt_aptATFMsesYY.draw();

  // CAPACITY - Airport ATFM arrival delay - MM - CHART
    var crt_aptATFMsesMM = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_aptATFMsesMM',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1k_t67KvHBoUAa42kdHK2AtT1YiW_zOTOw_rXMjeFsBw/edit?usp=sharing&sheet=APT_ATFM_SES_MM&range=A5:G65&tq=where%20G%3D1',
        options: {
            width: 450,
            height: 190,
            chartArea: {
                left: 80,
                top: 30,
                width: '60%',
                height: '60%'
            },
            title: 'Airport arr. ATFM delays (SES-RP2 airports)',
            titleTextStyle: {
                color: 'grey',
                fontSize: 11
            },
            legend: {
                position: 'right',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            isStacked: 'true',
            series: {
                0: {
                    type: 'lines',
                    color: '#5D7CBA',
                    lineWidth: 1,
                    pointSize: 6
                },
                1: {
                    type: 'bars',
                    color: '#7DD2F2'
                }
            },
            vAxis: {
                title: 'minutes per arrival',
                format: '0.00',
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            'columns': [1, 5, 2]
        }
    });
    crt_aptATFMsesMM.draw();

  // CAPACITY - Airport ATFM arrival delay - LOC - TABLE
    var tbl_aptATFM_LOC = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATFM_LOC',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1k_t67KvHBoUAa42kdHK2AtT1YiW_zOTOw_rXMjeFsBw/edit?usp=sharing&sheet=APT_ATFM_LOC&range=A5:G35',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 1, 2, 3, 4]
        }
    });
    tbl_aptATFM_LOC.draw();

  // CAPACITY - Airport ATFM arrival delay - APT - TABLE
    var tbl_aptATFM_APT = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATFM_APT',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1k_t67KvHBoUAa42kdHK2AtT1YiW_zOTOw_rXMjeFsBw/edit?usp=sharing&sheet=APT_ATFM_APT&range=A5:F180',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [1, 2, 0, 3]
        }
    });
    tbl_aptATFM_APT.draw();


  // CAPACITY - Airport ATFM slot adherence LOC - TABLE
    var tbl_aptATFMADH_LOC = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATFMADH_LOC',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1DSf9mb4qpaw6efb_SkjOQ3bB94NaOtsDFVDWPFzrnBs/edit?usp=sharing&sheet=APT_ATFM_ADH_LOC&range=A5:B35',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 1]
        }
    });
    tbl_aptATFMADH_LOC.draw();

  // CAPACITY - Airport ATFM slot adherence APT - TABLE
    var tbl_aptATFMADH_APT = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATFMADH_APT',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1DSf9mb4qpaw6efb_SkjOQ3bB94NaOtsDFVDWPFzrnBs/edit?usp=sharing&sheet=APT_ATFM_ADH_APT&range=A5:D180',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [1, 2, 0, 3]
        }
    });
    tbl_aptATFMADH_APT.draw();

  // CAPACITY - Airport ATC pre-departure LOC - TABLE
    var tbl_aptATC_LOC = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATC_LOC',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/11HPPi18jFe13pKtoSGjm8V9bpDVkt5d04lzwe-TSAq4/edit?usp=sharing&sheet=APT_ATC_PRE_LOC&range=A5:E35',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [0, 4, 1]
        }
    });
    tbl_aptATC_LOC.draw();

  // CAPACITY - Airport ATC pre-departure APT - TABLE
    var tbl_aptATC_APT = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_aptATC_APT',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/11HPPi18jFe13pKtoSGjm8V9bpDVkt5d04lzwe-TSAq4/edit?usp=sharing&sheet=APT_ATC_PRE_APT&range=A5:F180',
        options: {
            allowHtml: true,
            width: 470,
            height: 280
        },
        view: {
            columns: [1, 2, 0, 3]
        }
    });
    tbl_aptATC_APT.draw();

  // ERT SU - TABLE
    var tbl_ertSU = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ertSU',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1BuKxFalLn9bWhHULZxns8ikkZmRRWWpd6CoqsAuBec0/edit?usp=sharing&sheet=ERT_SU_CZ&range=A5:I36',
        options: {
            allowHtml: true,
            width: 470,
            height: 400
        },
        view: {
            columns: [0, 3, 6, 8, 5]
        }
    });
    tbl_ertSU.draw();

  // ERT SU - YY - CHART vs target - [EU_YY]
    var crt_ertSUYYvstgt = new google.visualization.ChartWrapper({
        chartType: 'ComboChart',
        containerId: 'crt_ertSUYYvstgt',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1BuKxFalLn9bWhHULZxns8ikkZmRRWWpd6CoqsAuBec0/edit?usp=sharing&sheet=ERT_SU_CZ&range=A5:I36',
        options: {
            width: 475,
            height: 400,
            chartArea: {
                left: 55,
                top: 30,
                width: '80%',
                height: '50%'
            },
            titleTextStyle: {
                color: 'grey',
                fontSize: 12
            },
            legend: {
                position: 'bottom',
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            series: {
                0: {
                    type: 'bars',
                    color: '#7DD2F2'
                }
            },
            vAxis: {
                title: 'actual vs. determined ERT SU',
                format: '0%',
                viewWindow: {
                    min: -0.05,
                    max: 0.35
                },
                textStyle: {
                    color: 'grey',
                    fontSize: 11
                },
                titleTextStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            },
            hAxis: {
                slantedTextAngle: 90,
                textStyle: {
                    color: 'grey',
                    fontSize: 10
                }
            }
        },
        view: {
            'columns': [0, 8]
        }
    });
    crt_ertSUYYvstgt.draw();


 // ER CEF - STATE - TABLE
    var tbl_ertcef_state = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ertcef_state',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1NvqF2OiMmsH7LB01Or8_wrDCwq6cvwU6ysqyIMeG2MM/edit?usp=sharing&sheet=ERT_CEF_STATE&range=A2:AJ32&hl=en_GB',
        options: {
            allowHtml: true,
            width: 950,
            height: 280
        },
        view: {columns: [0, 29, 30,31,33,34,35]}
    });
    tbl_ertcef_state.draw();

 // ER CEF - FAB - TABLE
    var tbl_ertcef_fab = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_ertcef_fab',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1NvqF2OiMmsH7LB01Or8_wrDCwq6cvwU6ysqyIMeG2MM/edit?usp=sharing&sheet=ERT_CEF_FAB&range=A2:N11&hl=en_GB',
        options: {
            allowHtml: true,
            width: 950,
            height: 270
        },
        view: {columns: [0, 7, 8, 9,11,12,13]}
    });
    tbl_ertcef_fab.draw();

 // TRM CEF - TCZ - TABLE
    var tbl_trcef_state = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_trcef_state',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1Ub4oNRxPbE0wAIxWJ2wLmsmebHmvNQKiCAyVhCzjDlk/edit?usp=sharing&sheet=TRM_CEF_STATE&range=A2:AJ39&hl=en_GB',
        options: {
            allowHtml: true,
            width: 950,
            height: 280
        },
        view: {columns: [0, 29, 30,31,33,34,35]}
    });
    tbl_trcef_state.draw();

 // TRM CEF - FAB - TABLE
    var tbl_trcef_fab = new google.visualization.ChartWrapper({
        chartType: 'Table',
        containerId: 'tbl_trcef_fab',
        dataSourceUrl: 'https://docs.google.com/spreadsheets/d/1Ub4oNRxPbE0wAIxWJ2wLmsmebHmvNQKiCAyVhCzjDlk/edit?usp=sharing&sheet=TRM_CEF_FAB&range=A2:N11&hl=en_GB',
        options: {
            allowHtml: true,
            width: 950,
            height: 270
        },
        view: {columns: [0, 7, 8, 9,11,12,13]}
    });
    tbl_trcef_fab.draw();

}
google.setOnLoadCallback(drawVisualization)
</script>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="2" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;Traffic</div>
</td>
</tr>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Average daily IFR flights</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/16WgqQjV0jXiGI2TOPk2XKsRvrAtMrL_8p7t2Nr2k2PM/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Minutes_of_en_route_ATFM_delay_per_flight" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_ertfltsYY"></div>
<div style="float: left;" id="crt_ertfltsMM"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ertflts_YY"></div>
</tr>
</tbody>
</table>
<br>
</tbody>
</table>


<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">


<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;SAFETY</div>
<span style="color:#C0504D;">To be provided in line with the scheduled reporting cycle.</span>
</td>
</tr>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">



<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp; ENVIRONMENT</div>
</td>
</tr>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp;Environment KPI #1: Horizontal en-route flight efficiency [%]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1wiPo8B2UOyc3ULZJiBPVk1qGcRpId4WMfjoRaRotpVs/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Average_horizontal_en-route_inefficiency" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_flteffYY"></div>
<div style="float: left;" id="crt_flteffMM"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ert_flteff"></div>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Environment PI #1: Additional taxi-out time [minutes per departure]</div>
<span style="color:#C0504D;"></span>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-September</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1z7ZrWrFAW-y7NycuZ-_65FfV8J4xmAsgtHaNyyqIpSo/edit?usp=sharing&hl=en_GB" 
target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: PRU analysis; Airports</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Additional_time_in_taxi-out_phase" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_txdly_LOC"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_txdly_APT"></div>
</td>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Environment PI #2: Additional time in terminal airspace [minutes per arrival]</div>
<span style="color:#C0504D;"></span>
</td>
</tr>
<tr>

<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-September</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">

<a href="https://docs.google.com/spreadsheets/d/1MsscCX4tqDwskuuBdwmUK0GxL1fq9sVOuYS65yYybkc/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Airports; Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Arrival_sequencing_and_metering_area_%28ASMA%29_additional_time" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ASMAdly_LOC"></div>
<br> </td>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top" id="tbl_ASMAdly_APT"></div>
<br> </td>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Effective use of the civil / military airspace structures&nbsp;&nbsp;
<a href="http://prudata.webfactional.com/wiki/index.php/Effective_use_of_the_civil_/_military_airspace_structures" target="_blank">(Meta data)</a></div>
</td>
</tr>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div style="text-align: left; vertical-align: top;"><span style="color: rgb(102, 102, 102);">&nbsp;To be provided in line with the scheduled reporting cycle</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div class="head4">&nbsp;Environment PI #3: Effectiveness of booking procedures for FUA</div>
<div style="text-align: left; vertical-align: top;">
<span style="color: rgb(102, 102, 102);"> </span></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div class="head4">&nbsp;Environment PI #4: Rate of planning of conditional routes (CDRs)</div>
<div style="text-align: left; vertical-align: top;">
<span style="color: rgb(102, 102, 102);"><br>
</span></div>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div class="head4">&nbsp;Environment PI #5: Effective use of CDRs</div>
<div style="text-align: left; vertical-align: top;">
<span style="color: rgb(102, 102, 102);"> </span></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div class="head4"></div>
<div style="text-align: left; vertical-align: top;">
<span style="color: rgb(102, 102, 102);"><br>
</span></div>
</tr>
</tbody>
</table>
<br>
</tbody>
</table>
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;CAPACITY</div>
<span style="color:#C0504D;">Data does not take into account 2018 post-operations adjustments.</span>
</td>
</tr>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity KPI #1: En-route ATFM delay per flight [minutes per flight]</div>
</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>

<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1H4jmSgWZbOviUsPRjLrJCRqzdWA2kQ4AKetTS87qZWc/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>

</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Minutes_of_en-route_ATFM_delay_per_flight" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_ertdlyYY"></div>
<div style="float: left;" id="crt_ertdlyMM"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_ertdly_YYtgt"></div>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity KPI #2: Airport ATFM arrival delay per flight [min./arr.]</div>
<span style="color:#C0504D;">Data does not take into account 2018 post-operations adjustments.</span>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1k_t67KvHBoUAa42kdHK2AtT1YiW_zOTOw_rXMjeFsBw/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: PRU analysis; Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/Airport_ATFM_delay" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_aptATFMsesYY"></div>
<br>
<br>
<div style="float: top;" id="tbl_aptATFM_LOC"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: left;" id="crt_aptATFMsesMM"></div>
<br>
<br>
<div style="float: top;" id="tbl_aptATFM_APT"></div>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity PI #1: Adherence to ATFM slots [% flights inside the slot tolerance window of [-5, +10 min.]]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1DSf9mb4qpaw6efb_SkjOQ3bB94NaOtsDFVDWPFzrnBs/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">
Source: Network Manager</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/ATFM_slot_adherence" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATFMADH_LOC"></div>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATFMADH_APT"></div>
</tr>
</tbody>
</table>
<br>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Capacity PI #2: Air traffic control pre-departure delay [min. per dep.]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-September</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/11HPPi18jFe13pKtoSGjm8V9bpDVkt5d04lzwe-TSAq4/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: Airports</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/ATC_pre-departure_delay" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATC_LOC"></div>
</td>
<td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
<div style="float: top;" id="tbl_aptATC_APT"></div>
</td>
</tr>
</tbody>
</table>
<br>
</table>
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<div class="head2">&nbsp;COST-EFFICIENCY</div>
</td>
<tr>

<td colspan="4" rowspan="1">
<div class="head3">&nbsp; En-route Service Units (TSU)[actual vs. determined]</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-October</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1BuKxFalLn9bWhHULZxns8ikkZmRRWWpd6CoqsAuBec0/edit?usp=sharing" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: CRCO; EC; PRU analysis </div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
</span></div>
</td>
</tr>
<tr>
<td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
<div class="head4">&nbsp;En-route TSU: by charging zones (2017)</div>
<div style="text-align: left; vertical-align: top;">
<div style="float: top;" id="tbl_ertSU"></div>
<br>
</td>
<td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
<div class="head4">&nbsp;En-route TSU: actual vs. determined (2017)</div>
<div style="text-align: left; vertical-align: top;">
<div style="float: top;" id="crt_ertSUYYvstgt"></div>
</td>
</tr>
</tbody>
</table>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">
<div class="head3">&nbsp; Cost efficiency KPI #1: Determined unit cost (DUC) for en-route (ER) ANS</div>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December 2018</span></div>
</td>
<td>

<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1NvqF2OiMmsH7LB01Or8_wrDCwq6cvwU6ysqyIMeG2MM/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: States, CRCO</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/RP2_(2015-2019)" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<br>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<span style="color:#C0504D;">The figures shown below are expressed in real term (Euro 2009). The underlying data (currencies, etc.) are available in the download file.
(D)=Determined ; (A)=Actual
</span>
</td>
</tr>
</tbody>
</table>
<br>
<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_ertcef_state"></div>
</td>
<br>
</tr>
<br>
<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_ertcef_fab"></div>
</td>
</tr>
</tbody>
</table>
<br>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
<tbody>
<table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
<tbody>
<tr>
<td colspan="4" rowspan="1">

<div class="head3">&nbsp; Cost efficiency KPI #2: Determined unit cost (DUC) for terminal (TR) ANS</div>
<span style="color:#C0504D;">As of 2017, two terminal charging zones (TCZ) were established in France (TCZ1 Paris airports and TCZ2 Other airports) and Poland (TCZ1 Warsaw airport and TCZ2 Other airports) instead of one single TCZs comprising 60 airports in France and 15 airports in Poland in 2016.</span>
</td>
</tr>
<tr>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">
Period: January-December 2018</span></div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);">
<a href="https://docs.google.com/spreadsheets/d/1Ub4oNRxPbE0wAIxWJ2wLmsmebHmvNQKiCAyVhCzjDlk/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a>
</span></div>
</td>
<td>
<div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;">
Source: States, CRCO</div>
</td>
<td>
<div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);">
<a href="http://prudata.webfactional.com/wiki/index.php/RP2_(2015-2019)" target="_blank">[Meta data]</a>
</span></div>
</td>
</tr>
<br>
<tr>
<td colspan="4" rowspan="1" style="width: 950px">
<span style="color:#C0504D;">The figures shown below are expressed in real term (Euro 2009). The underlying data (currencies, etc.) are available in the download file.
(D)=Determined ; (A)=Actual
</span>
</td>
</tr>
</tbody>
</table>
<br>
<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_trcef_state"></div>
</td>
<br>
</tr>
<br>
<tr>
<td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;">
<div id="tbl_trcef_fab"></div>
</td>
</tr>
</tbody>
</table>

