---
title: "Reporting Period 3 - 2021 dashboard"
date: 2022-01-17
categories: ["dashboard"]
aliases:
  - /rp2_2021.html
extrajs: [
  "/javascript/load_google.js",
  "/javascript/draw_vis.js",
  "/javascript/2021/crt_ertfltsYY_21.js",
  "/javascript/2021/crt_ertfltsMM_21.js",
  "/javascript/2021/tbl_ertfltsYY_21.js",
  "/javascript/2021/crt_flteffYY_21.js",
  "/javascript/2021/crt_flteffMM_21.js",
  "/javascript/2021/tbl_ert_flteff_Fab_21.js",
  "/javascript/2021/tbl_ert_flteff_Loc_21.js",
  "/javascript/2021/tbl_txdly_APT_21.js",
  "/javascript/2021/tbl_ASMAdly_APT_21.js",
  "/javascript/2021/tbl_cdo_APT_21.js",
  "/javascript/2021/crt_ertdlyYY_21.js",
  "/javascript/2021/crt_ertdlyMM_21.js",
  "/javascript/2021/tbl_ertdly_FAB_21.js",
  "/javascript/2021/tbl_ertdly_LOC_21.js",
  "/javascript/2021/crt_aptATFM_YY_21.js",
  "/javascript/2021/crt_aptATFM_MM_21.js",
  "/javascript/2021/tbl_aptATFM_LOC_21.js",
  "/javascript/2021/tbl_aptATFM_APT_21.js",
  "/javascript/2021/tbl_aptATFMADH_LOC_21.js",
  "/javascript/2021/tbl_aptATFMADH_APT_21.js",
  "/javascript/2021/tbl_aptATC_APT_21.js",
  "/javascript/2021/tbl_ertSU_21.js",
  "/javascript/2021/crt_ertSUYYvstgt_21.js",
  "/javascript/2021/tbl_ertcef_21.js",
  "/javascript/2021/tbl_trcef_21.js",
  ]
---
<script type="text/javascript" src="//www.google.com/jsapi"></script>

The data and indicators for [reference period 3][ref3] are in accordance with [Commission Implementing Regulation (EU) 2019/317][no317_2019] of 11 February 2019 laying down a performance and charging scheme in the single European sky.

<small><span style="color:#C0504D;">Last update: 14. April 2022</small></span>
<!-- TRAFFIC -->
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
  <tbody>
  <tr>
  <td colspan="2" rowspan="1" style="width: 950px"><div class="head2">&nbsp;Traffic</div></td>
  </tr>
    <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
        <tbody>
        <tr>
        <td colspan="4" rowspan="1"><div class="head3">&nbsp; Average daily IFR flights</div></td>
        </tr>
        <tr>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1gkEjsO_Sdr7TX1dQzMNtzPGh9_1ZZLlufR1nY25Dtv0/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: Network Manager</div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/minutes-of-en-route-atfm-delay-per-flight.Rmd" >}}' target="_blank">[Meta data]</a></span></div></td>
        </tr>     
        <tr>
          <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
            <div id="crt_cap_ert_YY"></div>
            <div style="float: left;" id="crt_ertfltsYY_21"></div>
            <div style="float: left;" id="crt_ertfltsMM_21"></div></td>
          <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
          <div style="float: top;" id="tbl_ertfltsYY_21"></div></td>
        </tr>
      </tbody>
      </table>
</tbody>
</table>

<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
  <tbody>
  <tr>
    <td colspan="4" rowspan="1" style="width: 950px">
        <table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
        <tbody>
    <tr>
            <td colspan="4" rowspan="1" style="width: 950px"><div class="head2">&nbsp;SAFETY</div><small><span style="color:#C0504D;">
            To be provided in line with the scheduled reporting cycle.
       <!--   <ul>
              <li>SKPI#1: Effectiveness of Safety Management (EoSM)</li>
              <li>SPI#1: Separation Minima Infringements (SMI)</li>
              <li>SPI#2: Separation Minima Infringements (SMI) with any contributions from ATS or CNS</li>
              <li>SPI#3: Runway Incursions (RI)</li>
              <li>SPI#4: Runway Incursions with any contribution from ATS or CNS</li>
              <li>SPI#5: Application of automatic safety data recording</li>
            </ul>  -->
            </small></span></td>
  </tr>
  </tbody>
</table>

<!-- ENVIRONMENT-->
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
  <tbody>
  <tr>
  <td colspan="4" rowspan="1" style="width: 950px"><div class="head2">&nbsp; ENVIRONMENT</div></td>
   </tr>
   <!-- Horizontal en-route flight efficiency-->
   <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
     <tbody>
        <tr>
       <td colspan="4" rowspan="1"><div class="head3">&nbsp;Environment: Horizontal en-route flight efficiency [%]</div></td>
        </tr>
         <tr>
         <td colspan="4" rowspan="1" style="width: 950px"><small><span>
            <ul>
              <li>EKPI#1: KEA - Avg. horizontal en-route flight efficiency (actual trajectory)</li>
              <li>EPI#1: KEP - Avg. horizontal en-route flight efficiency (last filed flight plan)</li>
              <li>EPI#2: KES - Avg. horizontal en-route flight efficiency (shortest constrained trajectory)</li>
            </ul></small></span></td>
         </tr>
         <tr>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Ref. date: 31. Dec. 2021</span></div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1chZPN_ZiiqopxziglL6lcQhqBqIDPdZ0SHMqE8bjos8/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Network Manager</div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/average-horizontal-en-route-inefficiency.md" >}}' target="_blank">[Meta data]</a></span></div></td>
         </tr>
        <tr>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_flteffYY_21"></div><br>
                <div id="tbl_ert_flteff_Fab_21"></div></td>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_flteffMM_21"></div><br>
                <div id="tbl_ert_flteff_Loc_21"></div></td>
          </tr>
          </tbody>
     </table><br>
   <!-- Additional taxi-out time-->
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #3: Additional taxi-out time [min per dep.] - (airports >80k movements)</div><span style="color:#C0504D;"></span></td>
          </tr>
        <!--<tr>
          <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data for August 2021 will only be available as of November 2021. This section will be updated as soon as the data is available.</span></div></small></td>
        </tr>-->
         <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/14rPN5WmyTXMN2aM-Zo48JK7sHZ0eVa0KAOdQU_JD3b8/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Airports</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/additional-taxi-out-time.html" >}}' target="_blank">[Meta data]</a></span></div></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1" style="vertical-align: top;"><div id="tbl_txdly_APT_21"></div></td>
          </tr>
          </tbody>
        </table><br>
    <!-- Additional ASMA time-->
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #4: Additional time in terminal airspace [min per arr.] - (airports >80k movements)</div><span style="color:#C0504D;"></span></td>
          </tr>
        <!--<tr>
          <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data for August 2021 will only be available as of November 2021. This section will be updated as soon as the data is available.</span></div></small></td>
          </tr>-->
        <tr>
          <td colspan="4" rowspan="1" style="width: 950px"></td>
        </tr>
        <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1Y397CS6bf7jV0asjZpDw1hecbT6_8cgRY7krXxdi7Y4/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Airports; Network Manager</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/additional-asma-time.html" >}}' target="_blank">[Meta data]</a></span></div></td>
        </tr>
        <tr>
            <td colspan="4" rowspan="1" style="vertical-align: top;"><div id="tbl_ASMAdly_APT_21"></div></td>
        </tr>
          </tbody>
      </table>  <br>
    <!-- Share of arrivals applying CDO -->
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #5: Share of arrivals applying CDO [% arrivals] - (all included airports)</div><span style="color:#C0504D;"></span></td>
          </tr>
    <!--  <tr>
          <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data for September is not yet available due to processing issues. The section will be updated as soon as the data is available.</span></div></small></td>
          </tr> -->
          <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1lliRCu97aoLP5VnVHsocl66uXEAS5vkONBtbPVE-f7w/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Airports; Network Manager</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"> </span></div></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1" style="vertical-align: top;"><div id="tbl_cdo_APT_21"></div></td>
          </tr>
          </tbody>
        </table><br>
 <!-- Use of share airspace etc -->
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #6: Effective use of reserved or segregated airspace</div><span style="color:#C0504D;"></span></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data not yet available. The section will be updated as soon as the data is available.</span></div></small></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #7: Rate of planning via available airspace structures (reserved or seg. and CDRs)</div><span style="color:#C0504D;"></span></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data not yet available. The section will be updated as soon as the data is available.</span></div></small></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Environment EPI #8: Rate of using available airspace structures (reserved or segregated and CDRs)</div><span style="color:#C0504D;"></span></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data not yet available. The section will be updated as soon as the data is available.</span></div></small></td>
          </tr>
          </tbody>
        </table>
    </tbody>
</table>

<!-- CAPACITY-->
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
  <tbody>
    <tr>
      <td colspan="4" rowspan="1" style="width: 950px"><div class="head2">&nbsp;CAPACITY</div></td>
    </tr>
      <!-- EN-ROUTE ATFM DELAYS-->
       <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Capacity CKPI #1: En-route ATFM delay per flight [minutes per flight]</div></td>
          </tr>
          <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/17RZ2YyVlMuvla3b2e14duSpv-hzXV5tYrDDuoBXw6CA/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Network Manager</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/minutes-of-en-route-atfm-delay-per-flight.md" >}}' target="_blank">[Meta data]</a></span></div></td>
          </tr>
          <tr>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_ertdlyYY_21"></div><br>
                <div id="tbl_ertdly_FAB_21"></div></td>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_ertdlyMM_21"></div><br>
                <div id="tbl_ertdly_LOC_21"></div></td>
          </tr>
          </tbody>
        </table>  <br>
      <!-- AIRPORT ATFM ARRIVAL DELAYS-->
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Capacity CKPI #2: Airport ATFM arrival delay per flight [min./arr.]</div></td>
          </tr>
          <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1tVWwaOS54a8a3WIT_cv49gxu40Lfh2hiwYvNu89qIuA/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: PRU analysis; Network Manager</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/airport-atfm-delay.md" >}}' target="_blank">[Meta data]</a></span></div></td>
          </tr>
          <tr>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_aptATFM_YY_21"></div><br>
                <div id="tbl_aptATFM_LOC_21"></div></td>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div id="crt_aptATFM_MM_21"></div><br>
                <div id="tbl_aptATFM_APT_21"></div></td>
          </tr>
          </tbody>
        </table>
    <br>
      <!-- ADHERENCE TO ATFM SLOTS--> 
        <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
          <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; Capacity CPI #2: Adherence to ATFM slots [% flights inside the slot tolerance window of [-5, +10 min.]]</div></td>
          </tr>
          <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1d5kJuIYm0m9OZ6FXoFZRuiwN7ZJhpn4s54PTM16pUq0/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: Network Manager</div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/atfm-slot-adherence.md" >}}' target="_blank">[Meta data]</a></span></div></td>
          </tr>
          <tr>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div style="float: top;" id="tbl_aptATFMADH_LOC_21"></div></td>
            <td colspan="2" rowspan="1" style="width: 475px; vertical-align: top;">
                <div style="float: top;" id="tbl_aptATFMADH_APT_21"></div></td>
          </tr>
          </tbody>
        </table>
  <br>
    <!-- ATC PRE DEPARTURE DELAYS-->
      <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
        <tbody>
        <tr>
          <td colspan="4" rowspan="1"><div class="head3">&nbsp; Capacity CPI #3: Air traffic control pre-departure delay [min. per dep.] - (airports >80k movements)<br>&nbsp; &nbsp;Capacity CPI #4: Average time of all cause-departure delay per flight [min. per dep.] - (airports >80k movements)</div></td>
        </tr>
       <!-- <tr>
          <td colspan="4" rowspan="1" style="width: 950px"><div><span style="color:#C0504D;"><small>Data for August 2021 will only be available as of November 2021. This section will be updated as soon as the data is available.</span></div></small></td>
        </tr>-->
        <tr>
          <td colspan="4" rowspan="1" style="width: 950px"></td>
        </tr>
        <tr>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1WW-Xqv1uCnPrsYC14vevz9l60voi5tivGDQprvLx57w/edit?usp=sharing&hl=en_GB" target="_blank">[Download data]</a></span></div></td>
          <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: Airports</div></td>
          <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"><a href='{{< relref "/metadata/atc-pre-departure-delay.md" >}}' target="_blank">[Meta data]</a></span></div></td>
        </tr>
        <tr>
          <td colspan="4" rowspan="1"> 
              <div style="float: top;" id="tbl_aptATC_APT_21"></div></td>
        </tr>
        </tbody>
      </table>
</table><br>
<!-- COST-EFFICIENCY-->
<table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
  <tr>
    <td colspan="4" rowspan="1" style="width: 950px"><div class="head2">&nbsp;COST-EFFICIENCY</div></td>
  </tr>
   <!-- EN-ROUTE SERVICE UNITS-->
   <table style="width: 950px;" border="0" cellpadding="1" cellspacing="1">
        <tbody>
          <tr>
            <td colspan="4" rowspan="1"><div class="head3">&nbsp; En-route Service Units (TSU)[actual vs. determined]</div></td>
          </tr>
          <tr>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-period"> <span style="color:#C0504D;">Period: January-December</span></div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"><span style="color: rgb(102, 102, 102);"><a href="https://docs.google.com/spreadsheets/d/1h7Fkfl9VuTnIjw4BYotX2CNlPt2bLB8-bckUYn54Sog/edit?usp=sharing" target="_blank">[Download data]</a></span></div></td>
            <td><div style="width: 350px; text-align: left; background-color:#f7f8f9; vertical-align: top;" class="data-source">Source: CRCO; EC; PRU analysis </div></td>
            <td><div style="width: 120px; text-align: center; background-color:#f7f8f9; vertical-align: top;"> <span style="color: rgb(102, 102, 102);"></span></div></td>
          </tr>
          <tr>
            <td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
              <div class="head4">&nbsp;En-route TSU: by charging zones (2021)</div>
              <div style="float: top;" id="tbl_ertSU_21"></div></td>
            <td colspan="2" rowspan="1" style="width: 475px, text-align: center; vertical-align: top; ">
              <div class="head4">&nbsp;En-route TSU: actual vs. determined (2021)</div>
              <div style="float: top;" id="crt_ertSUYYvstgt_21"></div></td>
          </tr>
        </tbody>
      </table>
    <!-- DETERMINED UNIT COSTS FOR EN ROUTE ANS-->
       <table style="text-align: left; width: 950px;" border="0" cellpadding="1" cellspacing="1">
        <tr><td colspan="4" rowspan="1"><div class="head3">&nbsp; Cost efficiency KPI #1: Determined unit cost (DUC) for en-route (ER) ANS</div></td></tr><br>
        <tr><td colspan="4" rowspan="1"><span style="color:#C0504D;"><small>The en-route ANS costs in the table covers the period 2020 and 2021.</span><a href="https://docs.google.com/spreadsheets/d/1gp3bvboRGK2ne_KNm6Y0S1lPXL953R9GmsP1ytkrX2c/edit?usp=sharing" target="_blank"> The underlying data are available in the download file.</a></small></td></tr>
        <tr><td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;"><div id="tbl_ertcef_21"></div></td></tr>
     </table><br>
     <!-- DETERMINED UNIT COSTS FOR TERMINAL ANS-->
       <table style="text-align: left; width: 950px;" border="0" cellpadding="2" cellspacing="2">
        <tr><td colspan="4" rowspan="1"><div class="head3">&nbsp; Cost efficiency KPI #2: Determined unit cost (DUC) for terminal (TR) ANS</div></td></tr><br>
        <tr><td colspan="4" rowspan="1"><span style="color:#C0504D;"><small>The termial ANS costs in the table covers the period 2020 and 2021.</span><a href="https://docs.google.com/spreadsheets/d/1UFycNGPlOXpwtRzwSHtOj9fd2UM5l08_naNCbskWeGw/edit?usp=sharing" target="_blank"> The underlying data are available in the download file.</a></small></td></tr>
        <tr><td colspan="1" rowspan="1" style="width: 950px; vertical-align: top;"><div id="tbl_trcef_21"></div></td></tr>
      </table>

</table>

<script src="//d3js.org/d3.v3.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>


[no317_2019]: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2019.056.01.0001.01.ENG "IR 317/2019"
[ref3]: ../../metadata/rp3/ "Reference Period 3"